/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.swing.comun;

import controlador.datos.DBBConexion;
import aplicacion.facade.Facade;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 * Ventana para Seleccionar la BDD que queremos utilizar y introducir usuario y contraseña.
 * @author Mario Codes Sánchez
 * @since 24/11/2016
 */
public class VentanaLoginBDD extends javax.swing.JFrame {
    private String user, password, driver, url = "jdbc:mysql:";
    
    /**
     * Creates new form VentanaLoginBDD
     */
    public VentanaLoginBDD() {
        initComponents();
        
        this.setTitle("Log In");
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * Set del driver a utilizar y clases DAO segun conectemos y necesitemos de MySQL o Oracle.
     * Lo pongo en este de propio y no en el otro, porque necesito que se ejecute si o si una vez y cuando sea definitivo, no con un action que va cambiando.
     * @param seleccionBDD String con la BDD seleccionada.
     */
    private void seleccionarDriverCorrespondiente(String seleccionBDD) {
        Facade fachada = new Facade();
        
        switch(seleccionBDD) {
            case "MySQL":
                driver = "com.mysql.jdbc.Driver";
                fachada.cargadoPropertiesMySQL();
                break;
            case "Oracle XE":
                driver = "oracle.jdbc.driver.OracleDriver";
                fachada.cargadoPropertiesOracle();
                break;
            default:
                driver = "com.mysql.jdbc.Driver";
                JOptionPane.showMessageDialog(this, "Valor por defecto del switch. Error.");
                fachada.cargadoPropertiesMySQL();
                break;
        }
    }
    
    /**
     * Comprobacion de que no se intente meter un user vacio.
     * @return True si no esta vacio.
     */
    private boolean checkUser() {
        return !this.jTextFieldInputUser.getText().isEmpty();
    }
    
    /**
     * Asignacion de variables con el input de la ventana por parte del User.
     */
    private void recogidaValoresVentana() {
        user = this.jTextFieldInputUser.getText();
        password = new String(this.jPasswordFieldInputPWD.getPassword()); //Forma de obtener el input de jPasswordField y hacerlo String.
        url += this.jTextFieldInputUrl.getText(); //Concateno la parte variable de la url a la parte fija (driver) que se ha de poner antes.
        
        seleccionarDriverCorrespondiente((String) this.jComboBoxSelectBDD.getSelectedItem());
    }
    
    /**
     * Metodo principal de ejecucion. Pillo datos, intento la conexion y si no hay error, sigue adelante.
     */
    private void logeoBDD() {
        recogidaValoresVentana();
        
        if(checkUser()) {
            Connection conResultado = DBBConexion.getConexionDBBSingletonPattern(driver, url, user, password); //Instanciacion de la conexion por primera y unica vez (Patron Singleton).
            if(conResultado != null) { //Comprobacion de si la conexion es nula.
                VentanaPrincipal vp = SingletonVentanas.getVentanaPrincipalObtencionSingleton(); //Instanciacion de la VentanaPrincipal y puesta en marcha.
                enableBotonesHabitacionVentanaPrincipal(vp);
                vp.setTitle("Ventana Principal - Version BDD");
                vp.setVisible(true);
                this.dispose(); //Cerramos esta ventana.
            } //Quito el else de aqui. Ya informo al usuario cuando se produce el error de conex. en la clase DBBConexion.
        } else {
            JOptionPane.showMessageDialog(this, "Introduce un Usuario.");
        }
    }
    
    /**
     * Para cuando vuelva de JSON a BDD, reactivacion.
     * @param vp 
     */
    private void enableBotonesHabitacionVentanaPrincipal(VentanaPrincipal vp) {
        vp.getBotonAltaHabitacion().setEnabled(true);
        vp.getBotonBajaHabitacion().setEnabled(true);
        vp.getBotonListadoCompletoHabitaciones().setEnabled(true);
        vp.getBotonHabitacionesPrecio().setEnabled(true);
        vp.getBotonModificacionHabitacion().setEnabled(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jTextFieldInputUser = new javax.swing.JTextField();
        jLabelPWD = new javax.swing.JLabel();
        jPasswordFieldInputPWD = new javax.swing.JPasswordField();
        jLabelBDD = new javax.swing.JLabel();
        jComboBoxSelectBDD = new javax.swing.JComboBox();
        jButtonLogin = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jLabelUrl = new javax.swing.JLabel();
        jTextFieldInputUrl = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelTitulo.setText("Login Base de Datos");

        jLabelUser.setText("Usuario");

        jTextFieldInputUser.setText("root");

        jLabelPWD.setText("Contraseña");

        jLabelBDD.setText("Database");

        jComboBoxSelectBDD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MySQL", "Oracle XE" }));
        jComboBoxSelectBDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectBDDActionPerformed(evt);
            }
        });

        jButtonLogin.setText("Aceptar");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jButtonAtras.setText("Atras");
        jButtonAtras.setMaximumSize(new java.awt.Dimension(71, 23));
        jButtonAtras.setMinimumSize(new java.awt.Dimension(71, 23));
        jButtonAtras.setPreferredSize(new java.awt.Dimension(71, 23));
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        jLabelUrl.setText("Url");

        jTextFieldInputUrl.setText("//localhost/proyecto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxSelectBDD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelTitulo)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelPWD)
                                .addComponent(jLabelUrl)
                                .addComponent(jLabelUser)
                                .addComponent(jLabelBDD))
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPasswordFieldInputPWD, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldInputUrl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addComponent(jTextFieldInputUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogin)
                .addGap(28, 28, 28)
                .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUser)
                    .addComponent(jTextFieldInputUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPWD)
                    .addComponent(jPasswordFieldInputPWD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUrl)
                    .addComponent(jTextFieldInputUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxSelectBDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBDD))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogin)
                    .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        this.dispose();
        SingletonVentanas.getVentanaModoEjecucionObtencionSingleton().setVisible(true);
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        logeoBDD();
        SingletonVentanas.getVentanaModoEjecucionObtencionSingleton().setVisible(false);
    }//GEN-LAST:event_jButtonLoginActionPerformed

    /**
     * Set de fields necesarios cuando el usuario cambia la BDD a conectar en el comboBox.
     */
    private void jComboBoxSelectBDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelectBDDActionPerformed
        String valorSeleccionado = (String) this.jComboBoxSelectBDD.getSelectedItem();
        
        switch(valorSeleccionado) {
            case "MySQL":
                url = "jdbc:mysql:";
                this.jTextFieldInputUser.setText("root");
                this.jTextFieldInputUrl.setText("//localhost/proyecto");
                break;
            case "Oracle XE":
                url = "jdbc:oracle:thin:@";
                this.jTextFieldInputUser.setText("dai3");
                this.jPasswordFieldInputPWD.setText("tiger");
                this.jTextFieldInputUrl.setText("172.30.160.190:1521/xe");
//                url = "jdbc:oracle:thin:@localhost:1521:xe"; //fixme: Cambio la URL a la del server de clase. Tenerlo en cuenta al trabajar en casa.
                break;
            default:
                this.jTextFieldInputUser.setText("root");
                this.jTextFieldInputUrl.setText("jdbc:mysql://localhost/proyecto");
                break;
        }
    }//GEN-LAST:event_jComboBoxSelectBDDActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JComboBox jComboBoxSelectBDD;
    private javax.swing.JLabel jLabelBDD;
    private javax.swing.JLabel jLabelPWD;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUrl;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPasswordField jPasswordFieldInputPWD;
    private javax.swing.JTextField jTextFieldInputUrl;
    private javax.swing.JTextField jTextFieldInputUser;
    // End of variables declaration//GEN-END:variables
}
