FROM mysql:5.6.23

ENV MYSQL_DATABASE project
ENV MYSQL_ROOT_PASSWORD root
ENV MYSQL_USER root
ENV MYSQL_ALLOW_EMPTY_PASSWORD yes

COPY db.sql /docker-entrypoint-initdb.d/db.sql
COPY my.cnf /etc/mysql/my.conf

RUN /entrypoint.sh mysqld & sleep 10 
RUN rm /docker-entrypoint-initdb.d/db.sql
