package dto;
// Generated 27-ene-2017 12:01:58 by Hibernate Tools 4.3.1



/**
 * VistaActividadesAlojamiento generated by hbm2java
 */
public class VistaActividadesAlojamiento  implements java.io.Serializable {


     private VistaActividadesAlojamientoId id;

    public VistaActividadesAlojamiento() {
    }

    public VistaActividadesAlojamiento(VistaActividadesAlojamientoId id) {
       this.id = id;
    }
   
    public VistaActividadesAlojamientoId getId() {
        return this.id;
    }
    
    public void setId(VistaActividadesAlojamientoId id) {
        this.id = id;
    }




}


