/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.ventanas;

/**
 * Ventana Principal que se ejecutara al inicio del programa. Realiza recogida de parametros y pasa el control a la ventana donde se ejecutara el resto.
 * @author Mario Codes Sánchez
 * @since 05/11/2016
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        
        this.setTitle("Introducir Parametros");
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloPrincipal = new javax.swing.JLabel();
        jPanel = new javax.swing.JPanel();
        jLabelProductores = new javax.swing.JLabel();
        jLabelConsumidores = new javax.swing.JLabel();
        jLabelMaxPila = new javax.swing.JLabel();
        jSpinnerInputTamanioPila = new javax.swing.JSpinner();
        jSpinnerInputProductores = new javax.swing.JSpinner();
        jSpinnerInputConsumidores = new javax.swing.JSpinner();
        jButtonEjecutar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jPanelParamExtra = new javax.swing.JPanel();
        jLabelTiempoThreadDormido = new javax.swing.JLabel();
        jSpinnerInputTiempoThreadDormido = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTituloPrincipal.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelTituloPrincipal.setText("Productores y Consumidores con Semáforo");

        jPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parámetros Principales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 2, 12))); // NOI18N

        jLabelProductores.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        jLabelProductores.setText("Numero de Productores:");

        jLabelConsumidores.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        jLabelConsumidores.setText("Numero de Consumidores:");

        jLabelMaxPila.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        jLabelMaxPila.setText("Tamaño Máximo de Pila");

        jSpinnerInputTamanioPila.setModel(new javax.swing.SpinnerNumberModel(9, 1, 99, 1));
        jSpinnerInputTamanioPila.setToolTipText("Cantidad de chars almacenables en el buffer");

        jSpinnerInputProductores.setModel(new javax.swing.SpinnerNumberModel(5, 0, 99, 1));
        jSpinnerInputProductores.setToolTipText("Productores ejecutando simultaneamente");

        jSpinnerInputConsumidores.setModel(new javax.swing.SpinnerNumberModel(3, 0, 99, 1));
        jSpinnerInputConsumidores.setToolTipText("Consumidores ejecutando simultaneamente");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelConsumidores)
                    .addComponent(jLabelMaxPila)
                    .addComponent(jLabelProductores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSpinnerInputProductores, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jSpinnerInputConsumidores)
                    .addComponent(jSpinnerInputTamanioPila, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerInputProductores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProductores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerInputConsumidores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConsumidores))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaxPila)
                    .addComponent(jSpinnerInputTamanioPila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        jButtonEjecutar.setText("Ejecutar");
        jButtonEjecutar.setToolTipText("Ejecutar el programa con los datos arriba establecidos");
        jButtonEjecutar.setPreferredSize(new java.awt.Dimension(120, 40));
        jButtonEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjecutarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setToolTipText("Cerrar el programa");
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(120, 40));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jPanelParamExtra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parámetros Extra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 12))); // NOI18N

        jLabelTiempoThreadDormido.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        jLabelTiempoThreadDormido.setText("Tiempo Thread Dormido (ms):");

        jSpinnerInputTiempoThreadDormido.setModel(new javax.swing.SpinnerNumberModel(2000, 0, 60000, 500));
        jSpinnerInputTiempoThreadDormido.setToolTipText("Tiempo en milisegundos que pasa cada productor y consumidor dormido entre ejecucion y ejecucion");

        javax.swing.GroupLayout jPanelParamExtraLayout = new javax.swing.GroupLayout(jPanelParamExtra);
        jPanelParamExtra.setLayout(jPanelParamExtraLayout);
        jPanelParamExtraLayout.setHorizontalGroup(
            jPanelParamExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParamExtraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTiempoThreadDormido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerInputTiempoThreadDormido, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelParamExtraLayout.setVerticalGroup(
            jPanelParamExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParamExtraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelParamExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTiempoThreadDormido)
                    .addComponent(jSpinnerInputTiempoThreadDormido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 23, Short.MAX_VALUE)
                        .addComponent(jLabelTituloPrincipal))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelParamExtra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButtonEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelParamExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        System.exit(0); //Cerrado del programa.
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjecutarActionPerformed
        //Recogida de input del usuario.
        int[] intArrayParametros = new int[4];
        
        intArrayParametros[0] = (int) jSpinnerInputTamanioPila.getValue();
        intArrayParametros[1] = (int) jSpinnerInputProductores.getValue();
        intArrayParametros[2] = (int) jSpinnerInputConsumidores.getValue();
        intArrayParametros[3] = (int) jSpinnerInputTiempoThreadDormido.getValue();
        
        //Creacion de la nueva ventana con este input.
        WindowEjecucion we = new WindowEjecucion(intArrayParametros);
    }//GEN-LAST:event_jButtonEjecutarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEjecutar;
    private javax.swing.JLabel jLabelConsumidores;
    private javax.swing.JLabel jLabelMaxPila;
    private javax.swing.JLabel jLabelProductores;
    private javax.swing.JLabel jLabelTiempoThreadDormido;
    private javax.swing.JLabel jLabelTituloPrincipal;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanelParamExtra;
    private javax.swing.JSpinner jSpinnerInputConsumidores;
    private javax.swing.JSpinner jSpinnerInputProductores;
    private javax.swing.JSpinner jSpinnerInputTamanioPila;
    private javax.swing.JSpinner jSpinnerInputTiempoThreadDormido;
    // End of variables declaration//GEN-END:variables
}
