package dto;
// Generated 31-ene-2017 13:00:46 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Habitacion generated by hbm2java
 */
public class Habitacion  implements java.io.Serializable {


     private int idHabitacion;
     private String extrasHabitacion;
     private long precio;
     private char cuartoBanio;
     private String tipoHabitacion;
     private String resenias;
     private int alojamientoIdAlojamiento;
     private Integer reservaIdReserva;

    public Habitacion() {
    }

	
    public Habitacion(int idHabitacion, char cuartoBanio, int alojamientoIdAlojamiento) {
        this.idHabitacion = idHabitacion;
        this.cuartoBanio = cuartoBanio;
        this.alojamientoIdAlojamiento = alojamientoIdAlojamiento;
    }
    public Habitacion(int idHabitacion, String extrasHabitacion, long precio, char cuartoBanio, String tipoHabitacion, String resenias, int alojamientoIdAlojamiento, Integer reservaIdReserva) {
       this.idHabitacion = idHabitacion;
       this.extrasHabitacion = extrasHabitacion;
       this.precio = precio;
       this.cuartoBanio = cuartoBanio;
       this.tipoHabitacion = tipoHabitacion;
       this.resenias = resenias;
       this.alojamientoIdAlojamiento = alojamientoIdAlojamiento;
       this.reservaIdReserva = reservaIdReserva;
    }
   
    public int getIdHabitacion() {
        return this.idHabitacion;
    }
    
    public void setIdHabitacion(int idHabitacion) {
        this.idHabitacion = idHabitacion;
    }
    public String getExtrasHabitacion() {
        return this.extrasHabitacion;
    }
    
    public void setExtrasHabitacion(String extrasHabitacion) {
        this.extrasHabitacion = extrasHabitacion;
    }
    public long getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(long precio) {
        this.precio = precio;
    }
    public char getCuartoBanio() {
        return this.cuartoBanio;
    }
    
    public void setCuartoBanio(char cuartoBanio) {
        this.cuartoBanio = cuartoBanio;
    }
    public String getTipoHabitacion() {
        return this.tipoHabitacion;
    }
    
    public void setTipoHabitacion(String tipoHabitacion) {
        this.tipoHabitacion = tipoHabitacion;
    }
    public String getResenias() {
        return this.resenias;
    }
    
    public void setResenias(String resenias) {
        this.resenias = resenias;
    }
    public int getAlojamientoIdAlojamiento() {
        return this.alojamientoIdAlojamiento;
    }
    
    public void setAlojamientoIdAlojamiento(int alojamientoIdAlojamiento) {
        this.alojamientoIdAlojamiento = alojamientoIdAlojamiento;
    }
    public Integer getReservaIdReserva() {
        return this.reservaIdReserva;
    }
    
    public void setReservaIdReserva(Integer reservaIdReserva) {
        this.reservaIdReserva = reservaIdReserva;
    }




}


