/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.swing.alojamientos;

import controlador.datos.NeoDatis;
import controlador.dto.Alojamiento;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class VentanaShowAlojamiento extends javax.swing.JFrame {
    Alojamiento alojamiento;
    
    /**
     * Creates new form VentanaShowAlojamiento
     */
    public VentanaShowAlojamiento(Alojamiento alojamiento) {
        initComponents();
        
        this.setTitle("Comprueba los datos por favor.");
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        this.alojamiento = alojamiento;
        cargadoDatosAlojamiento(alojamiento);
    }

    /**
     * Rellena la ventana con los datos de AlojamientoDTO pasado por contructor.
     * @param alDTO Alojamiento cuyos datos se mostraran en la ventana.
     */
    private void cargadoDatosAlojamiento(Alojamiento alDTO) {
        this.inputNombre.setText(alDTO.getNombre());
        this.inputDireccionSocial.setText(alDTO.getDireccionSocial());
        this.inputRazonSocial.setText(alDTO.getRazonSocial());
        this.inputTelefono.setText(alDTO.getTelefonoContacto());
        this.inputDescripcion.setText(alDTO.getDescripcion());
        this.sliderValoracion.setValue(alDTO.getValoracion());
        this.inputFecha.setText(alDTO.getFechaApertura());
        this.spinnerNumHabitaciones.setValue(alDTO.getNumHabitaciones());
        rellenoAutoProvincia(alDTO);
    }
    
    private void rellenoAutoProvincia(Alojamiento alDTO) {
        String provincia = alDTO.getProvincia();
        switch(provincia) {
            case "Huesca":
                this.inputBoxProvincia.setSelectedIndex(0);
                break;
            case "Zaragoza":
                this.inputBoxProvincia.setSelectedIndex(1);
                break;
            case "Teruel":
                this.inputBoxProvincia.setSelectedIndex(2);
                break;
            default:
                this.inputBoxProvincia.setSelectedIndex(0);
                JOptionPane.showMessageDialog(this, "ERROR. Problema con valor provincia.");
                break;
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputFecha = new javax.swing.JTextField();
        LabelFechaApertura = new javax.swing.JLabel();
        sliderValoracion = new javax.swing.JSlider();
        jLabelProvincia = new javax.swing.JLabel();
        jLabelNumHabitaciones = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        inputBoxProvincia = new javax.swing.JComboBox();
        spinnerNumHabitaciones = new javax.swing.JSpinner();
        inputNombre = new javax.swing.JTextField();
        jLabelValoracion = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        inputTelefono = new javax.swing.JTextField();
        jLabelDirSocial = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        inputDireccionSocial = new javax.swing.JTextField();
        inputDescripcion = new javax.swing.JTextField();
        jLabelRazonSocial = new javax.swing.JLabel();
        jLabelTituloVentana = new javax.swing.JLabel();
        inputRazonSocial = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputFecha.setText("dd/mm/yyyy");
        inputFecha.setToolTipText("Formato: dd/mm/yyyy");
        inputFecha.setEnabled(false);
        inputFecha.setMaximumSize(new java.awt.Dimension(85, 30));
        inputFecha.setMinimumSize(new java.awt.Dimension(85, 30));
        inputFecha.setPreferredSize(new java.awt.Dimension(85, 30));
        inputFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputFechaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputFechaFocusLost(evt);
            }
        });

        LabelFechaApertura.setText("Fecha Apertura*");

        sliderValoracion.setMajorTickSpacing(1);
        sliderValoracion.setMaximum(5);
        sliderValoracion.setMinimum(1);
        sliderValoracion.setPaintLabels(true);
        sliderValoracion.setSnapToTicks(true);
        sliderValoracion.setToolTipText("Valoracion media de los clientes");
        sliderValoracion.setValue(3);
        sliderValoracion.setEnabled(false);
        sliderValoracion.setMaximumSize(new java.awt.Dimension(311, 31));
        sliderValoracion.setMinimumSize(new java.awt.Dimension(311, 31));
        sliderValoracion.setPreferredSize(new java.awt.Dimension(311, 31));

        jLabelProvincia.setText("Provincia*");

        jLabelNumHabitaciones.setText("Num. Habitaciones*");

        jLabelNombre.setText("Nombre*");

        inputBoxProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Huesca", "Zaragoza", "Teruel" }));
        inputBoxProvincia.setToolTipText("Provincia donde esta ubicada el alojamiento");
        inputBoxProvincia.setEnabled(false);

        spinnerNumHabitaciones.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(0), null, Integer.valueOf(1)));
        spinnerNumHabitaciones.setEnabled(false);
        spinnerNumHabitaciones.setMaximumSize(new java.awt.Dimension(85, 30));
        spinnerNumHabitaciones.setMinimumSize(new java.awt.Dimension(85, 30));
        spinnerNumHabitaciones.setPreferredSize(new java.awt.Dimension(85, 30));

        inputNombre.setToolTipText("Nombre del alojamiento");
        inputNombre.setEnabled(false);
        inputNombre.setMaximumSize(new java.awt.Dimension(85, 30));
        inputNombre.setMinimumSize(new java.awt.Dimension(85, 30));
        inputNombre.setPreferredSize(new java.awt.Dimension(85, 30));

        jLabelValoracion.setText("Valoración*");

        jLabelTelefono.setText("Telefono*");

        inputTelefono.setToolTipText("Telefono de contacto");
        inputTelefono.setEnabled(false);
        inputTelefono.setMaximumSize(new java.awt.Dimension(85, 30));
        inputTelefono.setMinimumSize(new java.awt.Dimension(85, 30));
        inputTelefono.setPreferredSize(new java.awt.Dimension(85, 30));

        jLabelDirSocial.setText("Dir. Social*");

        jLabelDescripcion.setText("Descripción");

        inputDireccionSocial.setToolTipText("Direccion Social del alojamiento");
        inputDireccionSocial.setEnabled(false);
        inputDireccionSocial.setMaximumSize(new java.awt.Dimension(85, 30));
        inputDireccionSocial.setMinimumSize(new java.awt.Dimension(85, 30));
        inputDireccionSocial.setPreferredSize(new java.awt.Dimension(85, 30));

        inputDescripcion.setToolTipText("Descripcion breve de las caracteristicas del alojamiento.");
        inputDescripcion.setEnabled(false);
        inputDescripcion.setMaximumSize(new java.awt.Dimension(311, 79));
        inputDescripcion.setMinimumSize(new java.awt.Dimension(311, 79));
        inputDescripcion.setName(""); // NOI18N
        inputDescripcion.setPreferredSize(new java.awt.Dimension(311, 79));

        jLabelRazonSocial.setText("Razón Social*");

        jLabelTituloVentana.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelTituloVentana.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelTituloVentana.setText("Datos Alojamiento");

        inputRazonSocial.setToolTipText("Razon social del alojamiento");
        inputRazonSocial.setEnabled(false);
        inputRazonSocial.setMaximumSize(new java.awt.Dimension(85, 30));
        inputRazonSocial.setMinimumSize(new java.awt.Dimension(85, 30));
        inputRazonSocial.setPreferredSize(new java.awt.Dimension(85, 30));

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelValoracion)
                                        .addComponent(jLabelDescripcion))
                                    .addComponent(jLabelDirSocial, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabelProvincia, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabelTelefono))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(inputDescripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(sliderValoracion, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelTituloVentana)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(inputBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(inputDireccionSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(inputTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelFechaApertura)
                                            .addComponent(jLabelRazonSocial)
                                            .addComponent(jLabelNumHabitaciones))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerNumHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabelNombre)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelTituloVentana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputDireccionSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDirSocial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTelefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelProvincia)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRazonSocial)
                            .addComponent(inputRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNumHabitaciones)
                            .addComponent(spinnerNumHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelFechaApertura, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDescripcion))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderValoracion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelValoracion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputFechaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputFechaFocusGained

    }//GEN-LAST:event_inputFechaFocusGained

    private void inputFechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputFechaFocusLost

    }//GEN-LAST:event_inputFechaFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this, "¿Seguro?");
        if(opcion == 0) {
            NeoDatis.delete(alojamiento);
            JOptionPane.showMessageDialog(this, "Alojamiento Eliminado.");
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFechaApertura;
    protected javax.swing.JComboBox inputBoxProvincia;
    protected javax.swing.JTextField inputDescripcion;
    protected javax.swing.JTextField inputDireccionSocial;
    protected javax.swing.JTextField inputFecha;
    protected javax.swing.JTextField inputNombre;
    protected javax.swing.JTextField inputRazonSocial;
    protected javax.swing.JTextField inputTelefono;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelDirSocial;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumHabitaciones;
    private javax.swing.JLabel jLabelProvincia;
    private javax.swing.JLabel jLabelRazonSocial;
    private javax.swing.JLabel jLabelTelefono;
    protected javax.swing.JLabel jLabelTituloVentana;
    private javax.swing.JLabel jLabelValoracion;
    protected javax.swing.JSlider sliderValoracion;
    protected javax.swing.JSpinner spinnerNumHabitaciones;
    // End of variables declaration//GEN-END:variables
}
