package controlador.DTO;
// Generated 26-ene-2017 14:35:38 by Hibernate Tools 3.4.0.CR1

/**
 * VistaActividadesAlojamiento generated by hbm2java
 */
public class VistaActividadesAlojamiento implements java.io.Serializable {

	private VistaActividadesAlojamientoId id;

	public VistaActividadesAlojamiento() {
	}

	public VistaActividadesAlojamiento(VistaActividadesAlojamientoId id) {
		this.id = id;
	}

	public VistaActividadesAlojamientoId getId() {
		return this.id;
	}

	public void setId(VistaActividadesAlojamientoId id) {
		this.id = id;
	}

}
