/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import aplicacion.controlador.juego.Resolucion;
import aplicacion.patrones.Singleton;
import java.awt.Color;
import java.util.InputMismatchException;
import java.util.Scanner;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

/**
 * todo: acordarme de añadir al final de todo hints y demas para cada boton.
 * Ventana principal del programa.
 * @author Mario Codes Sánchez
 * @since 20/12/2016
 */
public class WindowJuego extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public WindowJuego() {
        initComponents();
        
        this.setTitle("¡Sudoku!");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        
        creacionLineasTablero(this.jTableJuego);
        creacionLineasTablero(this.jTableTrampas);
        
        centrarTextoCells();
    }

    /**
     * Centrado de las labels de las cells.
     */
    private void centrarTextoCells() {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        for (int i = 0; i < this.jTableTrampas.getColumnCount(); i++) {
            this.jTableJuego.getColumnModel().getColumn(i).setCellRenderer( centerRenderer );
            this.jTableTrampas.getColumnModel().getColumn(i).setCellRenderer( centerRenderer );
        }
        
        jTabbedPanePrincipal.setEnabledAt(1, false); //Para que la de juego ni la de trampas se puedan seleccionar salvo cuando se haya creado el juego..
        jTabbedPanePrincipal.setEnabledAt(2, false); 
        jTabbedPanePrincipal.setEnabledAt(3, false); 
    }
    
    /**
     * Metemos a mano las lineas adicionales del tablero.
     */
    private void creacionLineasTablero(JTable jTable) {
        int[][] parametrosLineasGraficas = new int[][] {{130, 0, 5, 400}, //Mapeado a mano, si se modifica la pantalla por cualquier cosa, habra que remapear.
                                                            {259, 0, 5, 400}, 
                                                            {0, 120, 400, 5},
                                                            {0, 242, 400, 5}};
        
        jTable.add(new LineaGraficaCuadrado(parametrosLineasGraficas[0][0], parametrosLineasGraficas[0][1], parametrosLineasGraficas[0][2], parametrosLineasGraficas[0][3]));
        jTable.add(new LineaGraficaCuadrado(parametrosLineasGraficas[1][0], parametrosLineasGraficas[1][1], parametrosLineasGraficas[1][2], parametrosLineasGraficas[1][3]));
        jTable.add(new LineaGraficaCuadrado(parametrosLineasGraficas[2][0], parametrosLineasGraficas[2][1], parametrosLineasGraficas[2][2], parametrosLineasGraficas[2][3]));
        jTable.add(new LineaGraficaCuadrado(parametrosLineasGraficas[3][0], parametrosLineasGraficas[3][1], parametrosLineasGraficas[3][2], parametrosLineasGraficas[3][3]));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPanePrincipal = new javax.swing.JTabbedPane();
        jPanelMenuOpcionesJuego = new javax.swing.JPanel();
        jButtonJugar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonRecomenzar = new javax.swing.JButton();
        jButtonSolventar = new javax.swing.JButton();
        jTableJuego = new javax.swing.JTable();
        jTableTrampas = new javax.swing.JTable();
        jPanelSolventar = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuOpciones = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuJuego = new javax.swing.JMenu();
        jMenuItemActivarTrampas = new javax.swing.JMenuItem();
        jMenuItemComprobar = new javax.swing.JMenuItem();
        jMenuTesteo = new javax.swing.JMenu();
        jMenuItemTesteoTablero = new javax.swing.JMenuItem();
        jMenuItemOcultarCasilla = new javax.swing.JMenuItem();
        jMenuAcercaDe = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPanePrincipal.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N

        jButtonJugar.setText("Jugar Partida");
        jButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabelTitulo.setText("Sudoku");

        jButtonRecomenzar.setText("Recomenzar Partida");
        jButtonRecomenzar.setEnabled(false);
        jButtonRecomenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecomenzarActionPerformed(evt);
            }
        });

        jButtonSolventar.setText("Solucionar Sudoku 'Custom'");
        jButtonSolventar.setEnabled(false);

        javax.swing.GroupLayout jPanelMenuOpcionesJuegoLayout = new javax.swing.GroupLayout(jPanelMenuOpcionesJuego);
        jPanelMenuOpcionesJuego.setLayout(jPanelMenuOpcionesJuegoLayout);
        jPanelMenuOpcionesJuegoLayout.setHorizontalGroup(
            jPanelMenuOpcionesJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuOpcionesJuegoLayout.createSequentialGroup()
                .addGroup(jPanelMenuOpcionesJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuOpcionesJuegoLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabelTitulo))
                    .addGroup(jPanelMenuOpcionesJuegoLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanelMenuOpcionesJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRecomenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSolventar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanelMenuOpcionesJuegoLayout.setVerticalGroup(
            jPanelMenuOpcionesJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuOpcionesJuegoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonJugar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRecomenzar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSolventar)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        jTabbedPanePrincipal.addTab("Menu Principal", jPanelMenuOpcionesJuego);

        jTableJuego.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTableJuego.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableJuego.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableJuego.setMinimumSize(new java.awt.Dimension(135, 333));
        jTableJuego.setPreferredSize(new java.awt.Dimension(400, 390));
        jTableJuego.setRowHeight(41);
        jTableJuego.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTabbedPanePrincipal.addTab("Juego", jTableJuego);

        jTableTrampas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTableTrampas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableTrampas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableTrampas.setColumnSelectionAllowed(true);
        jTableTrampas.setEnabled(false);
        jTableTrampas.setMinimumSize(new java.awt.Dimension(135, 351));
        jTableTrampas.setPreferredSize(new java.awt.Dimension(400, 390));
        jTableTrampas.setRowHeight(41);
        jTableTrampas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTabbedPanePrincipal.addTab("Trampas", jTableTrampas);

        javax.swing.GroupLayout jPanelSolventarLayout = new javax.swing.GroupLayout(jPanelSolventar);
        jPanelSolventar.setLayout(jPanelSolventarLayout);
        jPanelSolventarLayout.setHorizontalGroup(
            jPanelSolventarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );
        jPanelSolventarLayout.setVerticalGroup(
            jPanelSolventarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        jTabbedPanePrincipal.addTab("Solventar", jPanelSolventar);

        jMenuOpciones.setText("File");

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemSalir);

        jMenuBar.add(jMenuOpciones);

        jMenuJuego.setText("Juego");

        jMenuItemActivarTrampas.setText("Activar Trampas");
        jMenuItemActivarTrampas.setEnabled(false);
        jMenuItemActivarTrampas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemActivarTrampasActionPerformed(evt);
            }
        });
        jMenuJuego.add(jMenuItemActivarTrampas);

        jMenuItemComprobar.setText("Solventar Sudoku Actual");
        jMenuItemComprobar.setEnabled(false);
        jMenuItemComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemComprobarActionPerformed(evt);
            }
        });
        jMenuJuego.add(jMenuItemComprobar);

        jMenuBar.add(jMenuJuego);

        jMenuTesteo.setText("Testeo");

        jMenuItemTesteoTablero.setText("Print Tablero");
        jMenuItemTesteoTablero.setEnabled(false);
        jMenuItemTesteoTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTesteoTableroActionPerformed(evt);
            }
        });
        jMenuTesteo.add(jMenuItemTesteoTablero);

        jMenuItemOcultarCasilla.setText("Ocultar Casilla");
        jMenuItemOcultarCasilla.setEnabled(false);
        jMenuItemOcultarCasilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOcultarCasillaActionPerformed(evt);
            }
        });
        jMenuTesteo.add(jMenuItemOcultarCasilla);

        jMenuBar.add(jMenuTesteo);

        jMenuAcercaDe.setText("Acerca De...");
        jMenuBar.add(jMenuAcercaDe);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed
       
    private void jButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarActionPerformed
//        Singleton.getFacadeSingleton().ocultacionNumerosAleatorios();
        Singleton.getFacadeSingleton().generacionTablero(this.jTableJuego, false);
        Singleton.getFacadeSingleton().generacionTablero(this.jTableTrampas, true);
        this.jTabbedPanePrincipal.setEnabledAt(1, true);
        this.jTabbedPanePrincipal.setSelectedIndex(1);
        this.jButtonJugar.setEnabled(false);
        this.jButtonRecomenzar.setEnabled(true);
        this.jMenuItemTesteoTablero.setEnabled(true);
        this.jMenuItemActivarTrampas.setEnabled(true);
        this.jMenuItemComprobar.setEnabled(true);
        this.jMenuItemOcultarCasilla.setEnabled(true);
    }//GEN-LAST:event_jButtonJugarActionPerformed

    private void jMenuItemActivarTrampasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemActivarTrampasActionPerformed
        this.jTabbedPanePrincipal.setEnabledAt(2, true);
    }//GEN-LAST:event_jMenuItemActivarTrampasActionPerformed

    private void jButtonRecomenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecomenzarActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(this, "Se perdera el juego actual y se comenzara uno nuevo. ¿Seguro?", "Confirmacion", JOptionPane.YES_NO_OPTION);
        if(confirmacion == 0) {
            this.jButtonJugarActionPerformed(evt);

        }
    }//GEN-LAST:event_jButtonRecomenzarActionPerformed

    private void jMenuItemTesteoTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTesteoTableroActionPerformed
        System.out.println(Singleton.getTableroSingleton());
    }//GEN-LAST:event_jMenuItemTesteoTableroActionPerformed

    private void jMenuItemComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemComprobarActionPerformed
        Resolucion.solucionFuerzaBruta();
    }//GEN-LAST:event_jMenuItemComprobarActionPerformed

    private void jMenuItemOcultarCasillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOcultarCasillaActionPerformed
        Scanner scanner;
        int fila = -1, casilla = -1;
        
        System.out.println("Ocultar Casilla.");
        while(fila == -1 || casilla == -1) {
            scanner = new Scanner(System.in);
            try {
                System.out.print("\tNumero de fila: ");
                fila = scanner.nextInt();
                System.out.print("\tNumero de casilla SEGUN FILA: ");
                casilla = scanner.nextInt();
            }catch(InputMismatchException ex) {
                System.out.println("Dato no valido.");
            }
        }
        
        Singleton.getFacadeSingleton().ocultarCasilla(jTableJuego, fila, casilla);
    }//GEN-LAST:event_jMenuItemOcultarCasillaActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonJugar;
    private javax.swing.JButton jButtonRecomenzar;
    private javax.swing.JButton jButtonSolventar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JMenu jMenuAcercaDe;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemActivarTrampas;
    private javax.swing.JMenuItem jMenuItemComprobar;
    private javax.swing.JMenuItem jMenuItemOcultarCasilla;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemTesteoTablero;
    private javax.swing.JMenu jMenuJuego;
    private javax.swing.JMenu jMenuOpciones;
    private javax.swing.JMenu jMenuTesteo;
    private javax.swing.JPanel jPanelMenuOpcionesJuego;
    private javax.swing.JPanel jPanelSolventar;
    private javax.swing.JTabbedPane jTabbedPanePrincipal;
    private javax.swing.JTable jTableJuego;
    private javax.swing.JTable jTableTrampas;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Inner Class hecha unicamente para la representacion de las lineas graficas.
     */
    private class LineaGraficaCuadrado extends JPanel {        
        /**
         * Constructor por defecto.
         * @param ejeX Coordenadas del eje x.
         * @param ejeY Coordenadas del eje y.
         * @param ancho Ancho que ocupara la linea.
         * @param alto Alto de la linea.
         */
        public LineaGraficaCuadrado(int ejeX, int ejeY, int ancho, int alto) {
            setBackground(Color.black);
            this.setBounds(ejeX, ejeY, ancho, alto);
        }
    }

}
