create or replace view vista_actividades_alojamiento as (
  SELECT RE.ALOJAMIENTO_ID_ALOJAMIENTO as ID_ALOJAMIENTO, RE.ACTIVIDAD_ID_ACTIVIDAD as ID_ACTIVIDAD, AL.NOMBRE as NOMBRE_ALOJAMIENTO, AL.DESCRIPCION as DESCRIPCION_ALOJAMIENTO,
      AL.DIRECCION_SOCIAL, AL.RAZON_SOCIAL, AL.TELEFONO_CONTACTO, AL.VALORACION as VALORACION_ALOJAMIENTO, AL.FECHA_APERTURA, AL.NUM_HABITACIONES as NUMERO_HABITACIONES, AL.PROVINCIA, 
      AC.NOMBRE as NOMBRE_ACTIVIDAD, AC.DESCRIPCION as DESCRIPCION_ACTIVIDAD, AC.DIA_REALIZACION, AC.DIA_SEMANA, AC.HORA_INICIO, AC.HORA_FIN, AC.LOCALIZACION, AC.DIFICULTAD, AC.CAPACIDAD, AC.NOMBRE_GUIA
    FROM ALOJAMIENTO AL JOIN REALIZA RE
    ON (RE.ALOJAMIENTO_ID_ALOJAMIENTO = AL.ID_ALOJAMIENTO)
    JOIN ACTIVIDAD AC
    ON(AC.ID_ACTIVIDAD = RE.ACTIVIDAD_ID_ACTIVIDAD)
);