/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import aplicacion.facade.ContenedorSingletton;
import aplicacion.facade.Facade;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 * Ventana principal del programa.
 * @author Mario Codes Sánchez
 * @since 13/12/2016
 */
public class WindowJuego extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public WindowJuego() {
        initComponents();
        
        this.setTitle("¡Sudoku!");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        
        creacionLineasTablero(this.jTableJuego);
        creacionLineasTablero(this.jTableTrampas);
        
        centrarTextoCells();
    }

    /**
     * Centrado de las labels de las cells.
     */
    private void centrarTextoCells() {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        for (int i = 0; i < this.jTableTrampas.getColumnCount(); i++) {
            this.jTableTrampas.getColumnModel().getColumn(i).setCellRenderer( centerRenderer );
        }
        
        jTabbedPanePrincipal.setEnabledAt(1, false); //Para que la de juego ni la de trampas se puedan seleccionar salvo cuando se haya creado el juego..
        jTabbedPanePrincipal.setEnabledAt(2, false); 
    }
    
    /**
     * Metemos a mano las lineas adicionales del tablero.
     */
    private void creacionLineasTablero(JTable jTable) {
        int[][] parametrosLineasGraficas = new int[][] {{130, 0, 5, 400}, //Mapeado a mano, si se modifica la pantalla por cualquier cosa, habra que remapear.
                                                            {259, 0, 5, 400}, 
                                                            {0, 107, 400, 5},
                                                            {0, 218, 400, 5}};
        
        jTable.add(new LineaGraficaCuadrado(parametrosLineasGraficas[0][0], parametrosLineasGraficas[0][1], parametrosLineasGraficas[0][2], parametrosLineasGraficas[0][3]));
        jTable.add(new LineaGraficaCuadrado(parametrosLineasGraficas[1][0], parametrosLineasGraficas[1][1], parametrosLineasGraficas[1][2], parametrosLineasGraficas[1][3]));
        jTable.add(new LineaGraficaCuadrado(parametrosLineasGraficas[2][0], parametrosLineasGraficas[2][1], parametrosLineasGraficas[2][2], parametrosLineasGraficas[2][3]));
        jTable.add(new LineaGraficaCuadrado(parametrosLineasGraficas[3][0], parametrosLineasGraficas[3][1], parametrosLineasGraficas[3][2], parametrosLineasGraficas[3][3]));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPanePrincipal = new javax.swing.JTabbedPane();
        jPanelMenuOpcionesJuego = new javax.swing.JPanel();
        jButtonJugar = new javax.swing.JButton();
        jTableJuego = new javax.swing.JTable();
        jTableTrampas = new javax.swing.JTable();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuOpciones = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuAcercaDe = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPanePrincipal.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N

        jButtonJugar.setText("Jugar");
        jButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuOpcionesJuegoLayout = new javax.swing.GroupLayout(jPanelMenuOpcionesJuego);
        jPanelMenuOpcionesJuego.setLayout(jPanelMenuOpcionesJuegoLayout);
        jPanelMenuOpcionesJuegoLayout.setHorizontalGroup(
            jPanelMenuOpcionesJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuOpcionesJuegoLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jButtonJugar)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanelMenuOpcionesJuegoLayout.setVerticalGroup(
            jPanelMenuOpcionesJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuOpcionesJuegoLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jButtonJugar)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        jTabbedPanePrincipal.addTab("Menu Principal", jPanelMenuOpcionesJuego);

        jTableJuego.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTableJuego.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableJuego.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableJuego.setCellSelectionEnabled(false);
        jTableJuego.setColumnSelectionAllowed(true);
        jTableJuego.setMaximumSize(new java.awt.Dimension(2147483647, 333));
        jTableJuego.setMinimumSize(new java.awt.Dimension(135, 333));
        jTableJuego.setPreferredSize(new java.awt.Dimension(675, 333));
        jTableJuego.setRowHeight(37);
        jTableJuego.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableJuego.setShowHorizontalLines(true);
        jTableJuego.setShowVerticalLines(true);
        jTabbedPanePrincipal.addTab("Juego", jTableJuego);

        jTableTrampas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTableTrampas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableTrampas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableTrampas.setColumnSelectionAllowed(true);
        jTableTrampas.setRowHeight(37);
        jTableTrampas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableTrampas.setShowHorizontalLines(true);
        jTableTrampas.setShowVerticalLines(true);
        jTabbedPanePrincipal.addTab("Trampas", jTableTrampas);

        jMenuOpciones.setText("Opciones");

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemSalir);

        jMenuBar.add(jMenuOpciones);

        jMenuAcercaDe.setText("Acerca De...");
        jMenuBar.add(jMenuAcercaDe);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPanePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarActionPerformed
        ContenedorSingletton.getFacadeSingleton().generacionTablero(this.jTableTrampas);
        this.jTabbedPanePrincipal.setEnabledAt(1, true);
        this.jTabbedPanePrincipal.setEnabledAt(2, true);
        this.jTabbedPanePrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_jButtonJugarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonJugar;
    private javax.swing.JMenu jMenuAcercaDe;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuOpciones;
    private javax.swing.JPanel jPanelMenuOpcionesJuego;
    private javax.swing.JTabbedPane jTabbedPanePrincipal;
    private javax.swing.JTable jTableJuego;
    private javax.swing.JTable jTableTrampas;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Inner Class hecha unicamente para la representacion de las lineas graficas.
     */
    private class LineaGraficaCuadrado extends JPanel {        
        /**
         * Constructor por defecto.
         * @param ejeX Coordenadas del eje x.
         * @param ejeY Coordenadas del eje y.
         * @param ancho Ancho que ocupara la linea.
         * @param alto Alto de la linea.
         */
        public LineaGraficaCuadrado(int ejeX, int ejeY, int ancho, int alto) {
            setBackground(Color.black);
            this.setBounds(ejeX, ejeY, ancho, alto);
        }
    }

}
