/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.swing.comun;

import controlador.datos.Singleton;
import controlador.datos.DBBConexion;
import aplicacion.facade.Facade;
import entidades.HibernateUtil;
import entidades.VistaActividadesAlojamiento;
import entidades.VistaActividadesAlojamientoId;
import java.sql.Connection;
import javax.swing.JOptionPane;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

/**
 * Ventana para Seleccionar la BDD que queremos utilizar y introducir usuario y contraseña.
 * @author Mario Codes Sánchez
 * @since 24/11/2016
 */
public class VentanaLoginBDD extends javax.swing.JFrame {
    private String user, password, driver = "oracle.jdbc.driver.OracleDriver", url = "jdbc:oracle:thin:@";
    
    /**
     * Creates new form VentanaLoginBDD
     */
    public VentanaLoginBDD() {
        initComponents();
        
        this.setTitle("Log In");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
    /**
     * Comprobacion de que no se intente meter un user vacio.
     * @return True si no esta vacio.
     */
    private boolean checkUser() {
        return !this.jTextFieldInputUser.getText().isEmpty();
    }
    
    /**
     * Asignacion de variables con el input de la ventana por parte del User.
     */
    private void recogidaValoresVentana() {
        user = this.jTextFieldInputUser.getText();
        password = new String(this.jPasswordFieldInputPWD.getPassword()); //Forma de obtener el input de jPasswordField y hacerlo String.
        url += this.jTextFieldInputUrl.getText(); //Concateno la parte variable de la url a la parte fija (driver) que se ha de poner antes.
    }
    
    /**
     * Metodo principal de ejecucion. Pillo datos, intento la conexion y si no hay error, sigue adelante.
     */
    private void logeoBDD() {
        recogidaValoresVentana();
        
        if(checkUser()) {
            Connection conResultado = DBBConexion.getConexionDBBSingletonPattern(driver, url, user, password); //Instanciacion de la conexion por primera y unica vez (Patron Singleton).
            if(conResultado != null) { //Comprobacion de si la conexion es nula.
                VentanaPrincipal vp = Singleton.getVentanaPrincipalObtencionSingleton(); //Instanciacion de la VentanaPrincipal y puesta en marcha.
                vp.setTitle("Ventana Principal - Version BDD");
                vp.setVisible(true);
                this.dispose(); //Cerramos esta ventana.
            } //Quito el else de aqui. Ya informo al usuario cuando se produce el error de conex. en la clase DBBConexion.
        } else {
            JOptionPane.showMessageDialog(this, "Introduce un Usuario.");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jTextFieldInputUser = new javax.swing.JTextField();
        jLabelPWD = new javax.swing.JLabel();
        jPasswordFieldInputPWD = new javax.swing.JPasswordField();
        jLabelBDD = new javax.swing.JLabel();
        jComboBoxSelectBDD = new javax.swing.JComboBox();
        jButtonLogin = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jLabelUrl = new javax.swing.JLabel();
        jTextFieldInputUrl = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelTitulo.setText("Login Base de Datos");

        jLabelUser.setText("Usuario");

        jTextFieldInputUser.setText("dai4");

        jLabelPWD.setText("Contraseña");

        jPasswordFieldInputPWD.setText("tiger");
        jPasswordFieldInputPWD.setToolTipText("");

        jLabelBDD.setText("Database");

        jComboBoxSelectBDD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Oracle XE" }));

        jButtonLogin.setText("Aceptar");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jButtonAtras.setText("Atras");
        jButtonAtras.setMaximumSize(new java.awt.Dimension(71, 23));
        jButtonAtras.setMinimumSize(new java.awt.Dimension(71, 23));
        jButtonAtras.setPreferredSize(new java.awt.Dimension(71, 23));
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        jLabelUrl.setText("Url");

        jTextFieldInputUrl.setText("172.30.160.190:1521/XE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxSelectBDD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelTitulo)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelPWD)
                                .addComponent(jLabelUrl)
                                .addComponent(jLabelUser)
                                .addComponent(jLabelBDD))
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPasswordFieldInputPWD, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldInputUrl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addComponent(jTextFieldInputUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogin)
                .addGap(28, 28, 28)
                .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUser)
                    .addComponent(jTextFieldInputUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPWD)
                    .addComponent(jPasswordFieldInputPWD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUrl)
                    .addComponent(jTextFieldInputUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxSelectBDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBDD))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogin)
                    .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        logeoBDD();
    }//GEN-LAST:event_jButtonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLoginBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLoginBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLoginBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLoginBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLoginBDD().setVisible(true);
            }
        });
    }
    
    /*
     * @param args the command line arguments
     */
//    public static void main(String[] args) {
//        new VentanaLoginBDD();
//        SingletonVentanas.getVentanaPrincipalObtencionSingleton();
//        SessionFactory sf = HibernateUtil.getSessionFactory();
//        Session s = sf.openSession();
//        s.beginTransaction();
//        
//        VistaActividadesAlojamientoId vaid = new VistaActividadesAlojamientoId();
//        vaid.setIdAlojamiento(65);
//        vaid.setIdActividad(66);
//        vaid.setNombreAlojamiento("SUUU");
//        vaid.setDescripcionAlojamiento("SUU");
//        vaid.setDireccionSocial("SUU");
//        vaid.setRazonSocial("SUUU");
//        vaid.setTelefonoContacto("123");
//        vaid.setValoracionAlojamiento(8);
//        vaid.setFechaApertura("12");
//        vaid.setNumeroHabitaciones(1);
//        vaid.setProvincia("Huesca");
//        vaid.setNombreActividad("Kayak");
//        vaid.setDescripcionActividad("TEST");
//        vaid.setDiaRealizacion("12");
//        vaid.setDiaSemana("Lunes");
//        vaid.setHoraInicio("8:10");
//        vaid.setHoraFin("10:10");
//        vaid.setLocalizacion("Barbastro");
//        vaid.setDificultad(3);
//        vaid.setCapacidad("12");
//        vaid.setNombreGuia("Manolo");
//        
//        VistaActividadesAlojamiento va = new VistaActividadesAlojamiento();
//        va.setId(vaid);
//        
//        s.save(va);
//        s.getTransaction().commit();
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JComboBox jComboBoxSelectBDD;
    private javax.swing.JLabel jLabelBDD;
    private javax.swing.JLabel jLabelPWD;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUrl;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPasswordField jPasswordFieldInputPWD;
    private javax.swing.JTextField jTextFieldInputUrl;
    private javax.swing.JTextField jTextFieldInputUser;
    // End of variables declaration//GEN-END:variables
}
