/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.swing.tabla;

import vista.swing.comun.VentanaPrincipal;
//import controlador.DTO.HabitacionDTO;
import aplicacion.facade.Facade;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.Collection;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
//import vista.swing.comun.SingletonVentanas;

/**
 * @author Mario Codes Sánchez
 * @since 10/11/2016
 */
public class VentanaListadoHabitaciones extends javax.swing.JFrame {
    private float precio_max = -1;
    private DefaultTableModel model;
    
    public VentanaListadoHabitaciones() {
        initComponents();
        
        this.setTitle("");
        this.setVisible(true);
        this.setResizable(false);
        
        this.tabla.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
//        creacionTabla();
    }
    
    /**
     * Constructor por defecto que utilizare yo.
     * @param precioMax
     */
    public VentanaListadoHabitaciones(float precioMax) {
        initComponents(); //Ini necesario de los componentes intrinsecos de la ventana.
        this.precio_max = precioMax;
        
        this.setVisible(true);
        this.setResizable(false);
        
//        creacionTabla(precioMax); //Introduccion del ResultSet en la tabla.
    }

//    private void creacionTabla() {
//        Facade fachada = new Facade();
//        Collection<HabitacionDTO> col = fachada.listadoHabitaciones();
//        
//        rellenoTablaDatos(col);
//    }
//    
//    private void creacionTabla(float precioMax) {
//        Facade fachada = new Facade();
//        Collection<HabitacionDTO> col = fachada.listadoHabitaciones(precioMax);
//        
//        rellenoTablaDatos(col);
//    }
    
    /**
     * Metodo que se encarga de actualizar la tabla con el RestultSet que paso como parametro por el constructor.
     * Montado por mi cuenta googleando, explicado dentro.
     */
//    private void rellenoTablaDatos(Collection<HabitacionDTO> col) {
//        model = (DefaultTableModel) tabla.getModel(); //Hacemos un get del DefaultModel con el que creamos la tabla desde Swing.
//
//        try {
//            for(HabitacionDTO habDTO : col) { //Para cada objeto Alojamiento de la coleccion.
//                Object[] row = new Object[7]; //Creamos un objeto 'fila' con tantas columnas como tenga nuestra tabla (10 en este caso).
//                row[0] = habDTO.getId_habitacion(); //Para cada row, se va rellenando columna a columna con los datos.
//                row[1] = habDTO.getHabitacion_id_foranea_alojamiento();
//                row[2] = habDTO.getPrecio();
//                row[3] = habDTO.getTipo_habitacion();
//                row[4] = habDTO.isCuarto_banio() ? "Si" : "No";
//                row[5] = habDTO.getExtras_habitacion();
//                row[6] = habDTO.getResenias();
//                model.addRow(row); //Añade la fila ya rellena al modelo de la tabla.
//            }
//        }catch(NullPointerException ex) {
//            System.out.println("Error especifico: " +ex.getLocalizedMessage());
//            JOptionPane.showMessageDialog(this, "ERROR. NullPointerException.");
//        }
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        botonCerrar = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 0));

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTitulo.setText("Habitaciones Ordenadas por Precio");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Habitacion", "ID_Alojamiento", "Precio", "Tipo_Habitacion", "# Cuarto(s) Baño", "Extras", "Reseñas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setRowHeight(18);
        tabla.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(tabla);

        botonCerrar.setText("Cerrar");
        botonCerrar.setMaximumSize(new java.awt.Dimension(140, 38));
        botonCerrar.setMinimumSize(new java.awt.Dimension(140, 38));
        botonCerrar.setPreferredSize(new java.awt.Dimension(140, 38));
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        botonActualizar.setText("Actualizar");
        botonActualizar.setMaximumSize(new java.awt.Dimension(140, 38));
        botonActualizar.setMinimumSize(new java.awt.Dimension(140, 38));
        botonActualizar.setPreferredSize(new java.awt.Dimension(140, 38));
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(labelTitulo)
                .addGap(0, 205, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
//        model.setRowCount(0); //Hace un vaciado de la tabla. Despúes de ejecutar esto, se debera volver a rellenar o quedara vacia.
//        
//        if(precio_max == -1) { //En funcion de que version de la ventana se haya invocado, se debera ejecutar una u otra version del metodo sobrecargado.
//            creacionTabla();
//        } else {
//            creacionTabla(precio_max);
//        }
//        
//        JOptionPane.showMessageDialog(this, "Listado Actualizado");
    }//GEN-LAST:event_botonActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

}
