/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.ventanas;

import controlador.facade.Facade;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultCaret;

/**
 * Ventana principal de ejecucion. Muestra al usuario lo que esta pasando en el programa.
 * @author Mario Codes Sánchez
 * @since 17/11/2016
 * @version 1.1 - Mejorada la interfaz. Opciones de retomar hilos una vez parados.
 */
public class WindowEjecucion extends javax.swing.JFrame {
    private int[] parametrosEjecucion;
    
    /**
     * Creates new form WindowEjecucion
     * @param parametrosEjecucion Parametros introducidos por el usuario en la ventana anterior. Con ellos obtenemos las variables para pila, numeroThreads etc.
     */
    public WindowEjecucion(int[] parametrosEjecucion) {
        initComponents();
        
        this.setTitle("Ejecucion del Programa");
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.parametrosEjecucion = parametrosEjecucion;
        
        Facade.instanciacionYParametrosPilaProdCons(parametrosEjecucion);
        setLabelsIni(parametrosEjecucion);
    }

    /**
     * Set de los labels que hacen output de los parametros para que el usuario pueda comprobar la informacion introducida.
     * @param parametrosEjecucion Parametros recogidos por el programa.
     */
    private void setLabelsIni(int[] parametrosEjecucion) {
        this.jLabelOutputPila.setText(Integer.toString(parametrosEjecucion[0]));
        this.jLabelOutputProductores.setText(Integer.toString(parametrosEjecucion[1]));
        this.jLabelOutputConsumidores.setText(Integer.toString(parametrosEjecucion[2]));
        this.jLabelOutputThreadDormido.setText(Integer.toString(parametrosEjecucion[3]) +" ms");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloVentana = new javax.swing.JLabel();
        jPanelPila = new javax.swing.JPanel();
        jScrollPaneContenidoPila = new javax.swing.JScrollPane();
        jTextAreaOutputContenidoPila = new javax.swing.JTextArea();
        jPanelProductores = new javax.swing.JPanel();
        jScrollPaneEjecucion = new javax.swing.JScrollPane();
        jTextAreaOutputEjecucionProductores = new javax.swing.JTextArea();
        jPanelParametros = new javax.swing.JPanel();
        jLabelPila = new javax.swing.JLabel();
        jLabelProductores = new javax.swing.JLabel();
        jLabelConsumidores = new javax.swing.JLabel();
        jLabelOutputPila = new javax.swing.JLabel();
        jLabelOutputProductores = new javax.swing.JLabel();
        jLabelOutputConsumidores = new javax.swing.JLabel();
        jLabelThreadDormido = new javax.swing.JLabel();
        jLabelOutputThreadDormido = new javax.swing.JLabel();
        jButtonTerminar = new javax.swing.JButton();
        jPanelConsumidores = new javax.swing.JPanel();
        jScrollPaneConsumidores = new javax.swing.JScrollPane();
        jTextAreaOutputEjecucionConsumidores = new javax.swing.JTextArea();
        jPanelControlPrograma = new javax.swing.JPanel();
        jButtonPararPrograma = new javax.swing.JButton();
        jButtonMatarConsumidores = new javax.swing.JButton();
        jButtonMatarProductores = new javax.swing.JButton();
        jButtonComenzarConsumidores = new javax.swing.JButton();
        jButtonComenzarProductores = new javax.swing.JButton();
        jButtonComenzarTodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTituloVentana.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        jLabelTituloVentana.setText("Ejecucion Programa - Monitores v1.1");

        jPanelPila.setBorder(javax.swing.BorderFactory.createTitledBorder("Contenido Pila Actual"));

        jTextAreaOutputContenidoPila.setEditable(false);
        jTextAreaOutputContenidoPila.setColumns(10);
        jTextAreaOutputContenidoPila.setRows(5);
        jTextAreaOutputContenidoPila.setToolTipText("Contenido en tiempo real del buffer");
        jScrollPaneContenidoPila.setViewportView(jTextAreaOutputContenidoPila);

        javax.swing.GroupLayout jPanelPilaLayout = new javax.swing.GroupLayout(jPanelPila);
        jPanelPila.setLayout(jPanelPilaLayout);
        jPanelPilaLayout.setHorizontalGroup(
            jPanelPilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPilaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneContenidoPila, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanelPilaLayout.setVerticalGroup(
            jPanelPilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPilaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneContenidoPila)
                .addContainerGap())
        );

        jPanelProductores.setBorder(javax.swing.BorderFactory.createTitledBorder("Ejecución Productor(es)"));

        jTextAreaOutputEjecucionProductores.setEditable(false);
        jTextAreaOutputEjecucionProductores.setColumns(20);
        jTextAreaOutputEjecucionProductores.setRows(5);
        jTextAreaOutputEjecucionProductores.setToolTipText("Resultados en tiempo real de los Productores");
        jScrollPaneEjecucion.setViewportView(jTextAreaOutputEjecucionProductores);
        DefaultCaret caret = (DefaultCaret)jTextAreaOutputEjecucionProductores.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);

        javax.swing.GroupLayout jPanelProductoresLayout = new javax.swing.GroupLayout(jPanelProductores);
        jPanelProductores.setLayout(jPanelProductoresLayout);
        jPanelProductoresLayout.setHorizontalGroup(
            jPanelProductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneEjecucion, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelProductoresLayout.setVerticalGroup(
            jPanelProductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductoresLayout.createSequentialGroup()
                .addComponent(jScrollPaneEjecucion, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelParametros.setBorder(javax.swing.BorderFactory.createTitledBorder("Parametros"));

        jLabelPila.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        jLabelPila.setText("Tamaño de Pila:");

        jLabelProductores.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        jLabelProductores.setText("Productores:");

        jLabelConsumidores.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        jLabelConsumidores.setText("Consumidores:");

        jLabelOutputPila.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jLabelOutputProductores.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jLabelOutputConsumidores.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jLabelThreadDormido.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        jLabelThreadDormido.setText("Thread Dormido: ");

        jLabelOutputThreadDormido.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanelParametrosLayout = new javax.swing.GroupLayout(jPanelParametros);
        jPanelParametros.setLayout(jPanelParametrosLayout);
        jPanelParametrosLayout.setHorizontalGroup(
            jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelThreadDormido)
                    .addComponent(jLabelConsumidores)
                    .addComponent(jLabelProductores)
                    .addComponent(jLabelPila))
                .addGap(27, 27, 27)
                .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelParametrosLayout.createSequentialGroup()
                        .addComponent(jLabelOutputThreadDormido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanelParametrosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOutputProductores, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelParametrosLayout.createSequentialGroup()
                                .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelOutputPila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelOutputConsumidores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(9, 9, 9)))))
                .addGap(39, 39, 39))
        );
        jPanelParametrosLayout.setVerticalGroup(
            jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametrosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelPila)
                    .addComponent(jLabelOutputPila, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOutputProductores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProductores))
                .addGap(27, 27, 27)
                .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOutputConsumidores, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConsumidores))
                .addGap(28, 28, 28)
                .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelThreadDormido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelOutputThreadDormido, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jButtonTerminar.setText("Terminar");
        jButtonTerminar.setToolTipText("Termina la ejecucion del programa y cierra la ventana");
        jButtonTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTerminarActionPerformed(evt);
            }
        });

        jPanelConsumidores.setBorder(javax.swing.BorderFactory.createTitledBorder("Ejecución Consumidor(es)"));

        jTextAreaOutputEjecucionConsumidores.setEditable(false);
        jTextAreaOutputEjecucionConsumidores.setColumns(20);
        jTextAreaOutputEjecucionConsumidores.setRows(5);
        jTextAreaOutputEjecucionConsumidores.setToolTipText("Resultados en tiempo real de los Consumidores");
        jScrollPaneConsumidores.setViewportView(jTextAreaOutputEjecucionConsumidores);
        DefaultCaret caret2 = (DefaultCaret)jTextAreaOutputEjecucionConsumidores.getCaret();
        caret2.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);

        javax.swing.GroupLayout jPanelConsumidoresLayout = new javax.swing.GroupLayout(jPanelConsumidores);
        jPanelConsumidores.setLayout(jPanelConsumidoresLayout);
        jPanelConsumidoresLayout.setHorizontalGroup(
            jPanelConsumidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsumidoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneConsumidores, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelConsumidoresLayout.setVerticalGroup(
            jPanelConsumidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsumidoresLayout.createSequentialGroup()
                .addComponent(jScrollPaneConsumidores)
                .addContainerGap())
        );

        jPanelControlPrograma.setBorder(javax.swing.BorderFactory.createTitledBorder("Control Programa"));

        jButtonPararPrograma.setText("Parar de Golpe");
        jButtonPararPrograma.setToolTipText("Para todos los threads del programa");
        jButtonPararPrograma.setMaximumSize(new java.awt.Dimension(140, 50));
        jButtonPararPrograma.setMinimumSize(new java.awt.Dimension(140, 50));
        jButtonPararPrograma.setPreferredSize(new java.awt.Dimension(146, 50));
        jButtonPararPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPararProgramaActionPerformed(evt);
            }
        });

        jButtonMatarConsumidores.setText("Parar Consumidores");
        jButtonMatarConsumidores.setToolTipText("Para solo los Threads Consumidor");
        jButtonMatarConsumidores.setMaximumSize(new java.awt.Dimension(140, 50));
        jButtonMatarConsumidores.setMinimumSize(new java.awt.Dimension(140, 50));
        jButtonMatarConsumidores.setPreferredSize(new java.awt.Dimension(146, 50));
        jButtonMatarConsumidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMatarConsumidoresActionPerformed(evt);
            }
        });

        jButtonMatarProductores.setText("Parar Productores");
        jButtonMatarProductores.setToolTipText("Para los Thread Productor");
        jButtonMatarProductores.setMaximumSize(new java.awt.Dimension(140, 50));
        jButtonMatarProductores.setMinimumSize(new java.awt.Dimension(140, 50));
        jButtonMatarProductores.setPreferredSize(new java.awt.Dimension(146, 50));
        jButtonMatarProductores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMatarProductoresActionPerformed(evt);
            }
        });

        jButtonComenzarConsumidores.setText("Recomenzar Consumidores");
        jButtonComenzarConsumidores.setEnabled(false);
        jButtonComenzarConsumidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComenzarConsumidoresActionPerformed(evt);
            }
        });

        jButtonComenzarProductores.setText("Recomenzar Productores");
        jButtonComenzarProductores.setEnabled(false);
        jButtonComenzarProductores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComenzarProductoresActionPerformed(evt);
            }
        });

        jButtonComenzarTodos.setText("Recomenzar Todos");
        jButtonComenzarTodos.setEnabled(false);
        jButtonComenzarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComenzarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelControlProgramaLayout = new javax.swing.GroupLayout(jPanelControlPrograma);
        jPanelControlPrograma.setLayout(jPanelControlProgramaLayout);
        jPanelControlProgramaLayout.setHorizontalGroup(
            jPanelControlProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlProgramaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelControlProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonMatarProductores, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jButtonMatarConsumidores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPararPrograma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelControlProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonComenzarConsumidores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonComenzarProductores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonComenzarTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelControlProgramaLayout.setVerticalGroup(
            jPanelControlProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlProgramaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelControlProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPararPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonComenzarTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelControlProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonComenzarConsumidores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMatarConsumidores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelControlProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonComenzarProductores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMatarProductores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelParametros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelPila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelProductores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelConsumidores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelControlPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(jButtonTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jLabelTituloVentana)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloVentana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelParametros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelControlPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelConsumidores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelProductores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTerminarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonTerminarActionPerformed

    private void jButtonPararProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPararProgramaActionPerformed
        //Parada de todos los hilos y output al user.
        this.jButtonPararPrograma.setEnabled(false);
        this.jButtonMatarProductores.setEnabled(false);
        this.jButtonMatarConsumidores.setEnabled(false);
        this.jButtonComenzarTodos.setEnabled(true);
        this.jButtonComenzarConsumidores.setEnabled(true);
        this.jButtonComenzarProductores.setEnabled(true);
        
        Facade.pararEjecucionTodosHilos();
        JOptionPane.showMessageDialog(this, "Todos los hilos Parados");
    }//GEN-LAST:event_jButtonPararProgramaActionPerformed

    private void jButtonMatarConsumidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMatarConsumidoresActionPerformed
        //Parada de los consumidores y output al user.
        this.jButtonPararPrograma.setEnabled(false);
        this.jButtonMatarConsumidores.setEnabled(false);
        this.jButtonComenzarConsumidores.setEnabled(true);
        if(!this.jButtonMatarProductores.isEnabled()) this.jButtonComenzarTodos.setEnabled(true);
        
        Facade.pararConsumidores();
        JOptionPane.showMessageDialog(this, "Consumidores Parados");
    }//GEN-LAST:event_jButtonMatarConsumidoresActionPerformed

    private void jButtonMatarProductoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMatarProductoresActionPerformed
        //Parada de los productores y output al user.
        this.jButtonPararPrograma.setEnabled(false);
        this.jButtonMatarProductores.setEnabled(false);
        this.jButtonComenzarProductores.setEnabled(true);
        if(!this.jButtonMatarConsumidores.isEnabled()) this.jButtonComenzarTodos.setEnabled(true);
        
        Facade.pararProductores();
        JOptionPane.showMessageDialog(this, "Productores Parados");
    }//GEN-LAST:event_jButtonMatarProductoresActionPerformed

    private void jButtonComenzarConsumidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComenzarConsumidoresActionPerformed
        Facade.recomenzarConsumidores(this.parametrosEjecucion[2]);
        this.jButtonComenzarConsumidores.setEnabled(false);
        this.jButtonMatarConsumidores.setEnabled(true);
        if(this.jButtonMatarProductores.isEnabled()) this.jButtonPararPrograma.setEnabled(true);
        if(!this.jButtonComenzarProductores.isEnabled()) this.jButtonComenzarTodos.setEnabled(false);
        this.jButtonComenzarTodos.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Consumidores reanudados");
    }//GEN-LAST:event_jButtonComenzarConsumidoresActionPerformed

    private void jButtonComenzarProductoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComenzarProductoresActionPerformed
        Facade.recomenzarProductores(this.parametrosEjecucion[1]);
        this.jButtonComenzarProductores.setEnabled(false);
        this.jButtonMatarProductores.setEnabled(true);
        if(this.jButtonMatarConsumidores.isEnabled()) this.jButtonPararPrograma.setEnabled(true);
        if(!this.jButtonComenzarConsumidores.isEnabled()) this.jButtonComenzarTodos.setEnabled(false);
        this.jButtonComenzarTodos.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Productores reanudados");
    }//GEN-LAST:event_jButtonComenzarProductoresActionPerformed

    private void jButtonComenzarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComenzarTodosActionPerformed
        this.jButtonComenzarTodos.setEnabled(false);
        this.jButtonPararPrograma.setEnabled(true);
        this.jButtonMatarConsumidores.setEnabled(true);
        this.jButtonMatarProductores.setEnabled(true);
        this.jButtonComenzarConsumidores.setEnabled(false);
        this.jButtonComenzarProductores.setEnabled(false);
        
        Facade.recomenzarTodos(this.parametrosEjecucion[1], this.parametrosEjecucion[2]);
        JOptionPane.showMessageDialog(this, "Todos los hilos reanudados");
    }//GEN-LAST:event_jButtonComenzarTodosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComenzarConsumidores;
    private javax.swing.JButton jButtonComenzarProductores;
    private javax.swing.JButton jButtonComenzarTodos;
    private javax.swing.JButton jButtonMatarConsumidores;
    private javax.swing.JButton jButtonMatarProductores;
    private javax.swing.JButton jButtonPararPrograma;
    private javax.swing.JButton jButtonTerminar;
    private javax.swing.JLabel jLabelConsumidores;
    private javax.swing.JLabel jLabelOutputConsumidores;
    private javax.swing.JLabel jLabelOutputPila;
    private javax.swing.JLabel jLabelOutputProductores;
    private javax.swing.JLabel jLabelOutputThreadDormido;
    private javax.swing.JLabel jLabelPila;
    private javax.swing.JLabel jLabelProductores;
    private javax.swing.JLabel jLabelThreadDormido;
    private javax.swing.JLabel jLabelTituloVentana;
    private javax.swing.JPanel jPanelConsumidores;
    private javax.swing.JPanel jPanelControlPrograma;
    private javax.swing.JPanel jPanelParametros;
    private javax.swing.JPanel jPanelPila;
    private javax.swing.JPanel jPanelProductores;
    private javax.swing.JScrollPane jScrollPaneConsumidores;
    private javax.swing.JScrollPane jScrollPaneContenidoPila;
    private javax.swing.JScrollPane jScrollPaneEjecucion;
    public static javax.swing.JTextArea jTextAreaOutputContenidoPila;
    public static javax.swing.JTextArea jTextAreaOutputEjecucionConsumidores;
    public static javax.swing.JTextArea jTextAreaOutputEjecucionProductores;
    // End of variables declaration//GEN-END:variables
}
