/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.swing.vista;

/**
 *
 * @author Alumno
 */
public class VentanaAltaAlojamientoVista extends javax.swing.JFrame {
    /**
     * Creates new form VentanaAltaAlojamiento
     * @param VS
     */
    public VentanaAltaAlojamientoVista() {
        initComponents();
        
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDatosAlojamiento = new javax.swing.JPanel();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldInputTelefono = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldInputNombreAloj = new javax.swing.JTextField();
        jTextFieldInputDirSocial = new javax.swing.JTextField();
        jLabelDirSocial = new javax.swing.JLabel();
        jTextFieldInputRazonSocial = new javax.swing.JTextField();
        jLabelRazonSocial = new javax.swing.JLabel();
        jSpinnerValoracion = new javax.swing.JSpinner();
        jLabelValoracion = new javax.swing.JLabel();
        jLabelFechaApertura = new javax.swing.JLabel();
        jTextFieldInputFechaApertura = new javax.swing.JTextField();
        jLabelHabitaciones = new javax.swing.JLabel();
        jSpinnerHabitaciones = new javax.swing.JSpinner();
        jLabelProvincia = new javax.swing.JLabel();
        jComboBoxProvincia = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneInputDescripcionAloj = new javax.swing.JTextPane();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabelMainTitulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelDatosAlojamiento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Alojamiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 2, 12))); // NOI18N

        jLabelTelefono.setText("Telefono");

        jLabelNombre.setText("Nombre");

        jLabelDirSocial.setText("Dir. Social");

        jLabelRazonSocial.setText("Razon Social");

        jSpinnerValoracion.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        jLabelValoracion.setText("Valoracion");

        jLabelFechaApertura.setText("Fecha Apertura");

        jLabelHabitaciones.setText("Habitaciones");

        jSpinnerHabitaciones.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabelProvincia.setText("Provincia");

        jComboBoxProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Huesca", "Zaragoza", "Teruel" }));

        jScrollPane2.setViewportView(jTextPaneInputDescripcionAloj);

        jLabelDescripcion.setText("Descripcion");

        javax.swing.GroupLayout jPanelDatosAlojamientoLayout = new javax.swing.GroupLayout(jPanelDatosAlojamiento);
        jPanelDatosAlojamiento.setLayout(jPanelDatosAlojamientoLayout);
        jPanelDatosAlojamientoLayout.setHorizontalGroup(
            jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosAlojamientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelDatosAlojamientoLayout.createSequentialGroup()
                            .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelValoracion)
                                .addComponent(jLabelHabitaciones))
                            .addGap(12, 12, 12)
                            .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelDatosAlojamientoLayout.createSequentialGroup()
                                    .addComponent(jSpinnerHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelProvincia)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                    .addComponent(jComboBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelDatosAlojamientoLayout.createSequentialGroup()
                                    .addComponent(jSpinnerValoracion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelFechaApertura))))
                        .addComponent(jLabelDescripcion)
                        .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldInputFechaApertura, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelDatosAlojamientoLayout.createSequentialGroup()
                                .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelRazonSocial)
                                    .addComponent(jLabelDirSocial)
                                    .addComponent(jLabelTelefono)
                                    .addComponent(jLabelNombre))
                                .addGap(12, 12, 12)
                                .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldInputDirSocial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                    .addComponent(jTextFieldInputTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldInputNombreAloj, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldInputRazonSocial)))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosAlojamientoLayout.setVerticalGroup(
            jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosAlojamientoLayout.createSequentialGroup()
                .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldInputNombreAloj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInputTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInputDirSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDirSocial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInputRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRazonSocial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerValoracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelValoracion)
                    .addComponent(jLabelFechaApertura)
                    .addComponent(jTextFieldInputFechaApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHabitaciones)
                    .addComponent(jSpinnerHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProvincia)
                    .addComponent(jComboBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabelDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelMainTitulo.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelMainTitulo.setText("Alta Alojamiento");

        jButton1.setText("Añadir");

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelDatosAlojamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(27, 27, 27)
                        .addComponent(jButton2)
                        .addGap(110, 110, 110))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMainTitulo)
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMainTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDatosAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBoxProvincia;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelDirSocial;
    private javax.swing.JLabel jLabelFechaApertura;
    private javax.swing.JLabel jLabelHabitaciones;
    private javax.swing.JLabel jLabelMainTitulo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelProvincia;
    private javax.swing.JLabel jLabelRazonSocial;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelValoracion;
    private javax.swing.JPanel jPanelDatosAlojamiento;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerHabitaciones;
    private javax.swing.JSpinner jSpinnerValoracion;
    private javax.swing.JTextField jTextFieldInputDirSocial;
    private javax.swing.JTextField jTextFieldInputFechaApertura;
    private javax.swing.JTextField jTextFieldInputNombreAloj;
    private javax.swing.JTextField jTextFieldInputRazonSocial;
    private javax.swing.JTextField jTextFieldInputTelefono;
    private javax.swing.JTextPane jTextPaneInputDescripcionAloj;
    // End of variables declaration//GEN-END:variables
}
