create or replace view vista_actividades_alojamiento as (
  SELECT RE.ALOJAMIENTO_ID_ALOJAMIENTO as ID_ALOJAMIENTO, RE.ACTIVIDAD_ID_ACTIVIDAD as ID_ACTIVIDAD, AL.NOMBRE as NOMBRE_ALOJAMIENTO, AL.DIRECCION_SOCIAL, AL.RAZON_SOCIAL, AL.TELEFONO_CONTACTO, AC.NOMBRE as NOMBRE_ACTIVIDAD, AC.DESCRIPCION as DESCRIPCION_ACTIVIDAD, 
            AC.DIA_SEMANA, AC.LOCALIZACION, AC.DIFICULTAD, AC.CAPACIDAD
    FROM ALOJAMIENTO AL JOIN REALIZA RE
    ON (RE.ALOJAMIENTO_ID_ALOJAMIENTO = AL.ID_ALOJAMIENTO)
    JOIN ACTIVIDAD AC
    ON(AC.ID_ACTIVIDAD = RE.ACTIVIDAD_ID_ACTIVIDAD)
);