-- Borrado limpio para empezar de nuevo.
-- Vaciar las tablas enteras.
DELETE FROM HABITACION;
DELETE FROM ACTIVIDAD;
DELETE FROM RESERVA;
DELETE FROM TRABAJADOR;
DELETE FROM ALOJAMIENTO;

-- Borrado de tablas para reescribirlas.
DROP TABLE TRABAJADOR;
DROP TABLE REALIZA;
DROP TABLE ACTIVIDAD;
DROP TABLE HABITACION;
DROP TABLE ALOJAMIENTO;
DROP TABLE RESERVA;