/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package web;

import java.io.IOException;
import java.util.ArrayList;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

/**
 *
 * @author Mario
 */
public class in extends javax.swing.JFrame {
    private static Document document;
    private static Elements tabla, headersWeb, datos;
    
    private static ArrayList<String> headersTabla = new ArrayList<>();
    
    /**
     * Creates new form in
     */
    public in() {
        initComponents();
    }
    
    /**
     * Limpieza de los headers para obtener solo texto y no codigo.
     * @param element Element actual a tratar.
     * @return String con el nombre de la cabecera limpio.
     */
    private static String limpiezaHeaders(Element element) {
        String header = element.toString();
        header = header.substring(header.indexOf('>')+1);
        header = header.substring(0, header.indexOf('<'));
        
        return header;
    }
    
    /**
     * Tratamiento de los Headers para la tabla.
     * @param elements Elementos a tratar.
     * fixme: ver si lo puedo reaprovechar mas adelante.
     */
    private static void adecuacionHeaders(Elements elements) {
//        for (int i = 0; i < 6; i++) { //No se porque salen duplicados, los quito.
//            elements.remove(0);
//        }
        
        for(Element element: elements) {
            headersTabla.add(limpiezaHeaders(element));
        }
    }
    
    /**
     * Proceso de adecuacion y obtencion de datos de la web.
     */
    private static void adecuacionDatos() {
        adecuacionHeaders(headersWeb);
    }
    
    /**
     * Get de los elementos necesarios para el parse.
     */
    private static void iniElementos(String url) {
        try {
            document = Jsoup.connect(url).get(); //Selecciona el documento entero.
            tabla = document.select("table"); //De ese documento, pilla la tabla. Contiene los datos que nos interesan.
            headersWeb = document.select("thead tr th");
            datos = document.select("tr");
        }catch(IOException ex) {
            ex.printStackTrace();
        }
    }
    
    /**
     * Proceso entero de recoleccion y filtrado de los datos.
     * @param url Url a la que nos conectamos.
     */
    private static void recoleccion(String url) {
        iniElementos(url);
        adecuacionDatos();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new in().setVisible(true);
                recoleccion("https://es.finance.yahoo.com/actives?e=mc");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
