/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.swing.vista;

import dto.Actividad;

/**
 * Ventana para chequear los datos de la actividad.
 * @author Mario Codes Sánchez
 * @since 21/02/2017
 */
public class VentanaAltaActividadVista extends javax.swing.JFrame {
    private Actividad actividad;
    
    /**
     * Creates new form VentanaAltaActividadVista
     */
    public VentanaAltaActividadVista(Actividad actividad) {
        initComponents();
        
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        this.actividad = actividad;
        setDatos(actividad );
    }

    private void setDatos(Actividad actividad) {
        int id = actividad.getIdActividad();
        String nombre = actividad.getNombre();
        String fecha = actividad.getDiaRealizacion();
        String diaSemana = actividad.getDiaSemana();
        String horaIni = actividad.getHoraInicio();
        String horaFin = actividad.getHoraFin();
        int dificultad = actividad.getDificultad();
        String capacidad = actividad.getCapacidad();
        String localizacion = actividad.getLocalizacion();
        String guia = actividad.getNombreGuia();
        String descripcion = actividad.getDescripcion();
        
        this.jTextFieldInputIDActividad.setText(Integer.toString(id));
        if(nombre != null) this.jTextFieldInputNombreActiv.setText(nombre);
        if(fecha != null) this.jTextFieldInputFechaActiv.setText(fecha);
        if(diaSemana != null) this.jTextFieldInputDiaSemana.setText(diaSemana);
        if(horaIni != null) this.jTextFieldInputHoraInicioAc.setText(horaIni);
        if(horaFin != null) this.jTextFieldInputHoraFinActiv.setText(horaFin);
        this.jSpinnerDificultad.setValue(dificultad);
        if(capacidad != null) this.jSpinnerCapacidadActiv.setValue(Integer.parseInt(capacidad));
        if(localizacion != null) this.jTextFieldInputLocalizacion.setText(localizacion);
        if(guia != null) this.jTextFieldInputNombreGuia.setText(guia);
        if(descripcion != null) this.jTextPaneInputDescrip.setText(descripcion);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMainTitulo = new javax.swing.JLabel();
        jPanelDatosActividad = new javax.swing.JPanel();
        jLabelIDActiv = new javax.swing.JLabel();
        jTextFieldInputIDActividad = new javax.swing.JTextField();
        jLabelNombreAc = new javax.swing.JLabel();
        jTextFieldInputNombreActiv = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneInputDescrip = new javax.swing.JTextPane();
        jLabelDescripAc = new javax.swing.JLabel();
        jTextFieldInputDiaSemana = new javax.swing.JTextField();
        jLabelDiaSemana = new javax.swing.JLabel();
        jTextFieldInputFechaActiv = new javax.swing.JTextField();
        jLabelFechaAc = new javax.swing.JLabel();
        jTextFieldInputHoraInicioAc = new javax.swing.JTextField();
        jLabelHoraIni = new javax.swing.JLabel();
        jTextFieldInputHoraFinActiv = new javax.swing.JTextField();
        jLabelHoraFin = new javax.swing.JLabel();
        jSpinnerCapacidadActiv = new javax.swing.JSpinner();
        jLabelCapacidad = new javax.swing.JLabel();
        jSpinnerDificultad = new javax.swing.JSpinner();
        jLabelDificultad = new javax.swing.JLabel();
        jTextFieldInputLocalizacion = new javax.swing.JTextField();
        jLabelLocalizacion = new javax.swing.JLabel();
        jLabelNombreGuia = new javax.swing.JLabel();
        jTextFieldInputNombreGuia = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelMainTitulo.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelMainTitulo.setText("Comprobacion Datos Actividad");

        jPanelDatosActividad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Actividad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 2, 12))); // NOI18N

        jLabelIDActiv.setText("ID");

        jTextFieldInputIDActividad.setEnabled(false);

        jLabelNombreAc.setText("Nombre");

        jTextFieldInputNombreActiv.setEnabled(false);

        jTextPaneInputDescrip.setEnabled(false);
        jScrollPane1.setViewportView(jTextPaneInputDescrip);

        jLabelDescripAc.setText("Descripcion");

        jTextFieldInputDiaSemana.setEnabled(false);

        jLabelDiaSemana.setText("Dia Semana");

        jTextFieldInputFechaActiv.setEnabled(false);

        jLabelFechaAc.setText("Fecha");

        jTextFieldInputHoraInicioAc.setEnabled(false);

        jLabelHoraIni.setText("Hora Inicio");

        jTextFieldInputHoraFinActiv.setEnabled(false);

        jLabelHoraFin.setText("Hora Fin");

        jSpinnerCapacidadActiv.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));
        jSpinnerCapacidadActiv.setEnabled(false);

        jLabelCapacidad.setText("Capacidad");

        jSpinnerDificultad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jSpinnerDificultad.setEnabled(false);

        jLabelDificultad.setText("Dificultad");

        jTextFieldInputLocalizacion.setEnabled(false);

        jLabelLocalizacion.setText("Localizacion");

        jLabelNombreGuia.setText("Nombre Guia");

        jTextFieldInputNombreGuia.setEnabled(false);

        javax.swing.GroupLayout jPanelDatosActividadLayout = new javax.swing.GroupLayout(jPanelDatosActividad);
        jPanelDatosActividad.setLayout(jPanelDatosActividadLayout);
        jPanelDatosActividadLayout.setHorizontalGroup(
            jPanelDatosActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosActividadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosActividadLayout.createSequentialGroup()
                        .addComponent(jLabelLocalizacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldInputLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosActividadLayout.createSequentialGroup()
                        .addGroup(jPanelDatosActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosActividadLayout.createSequentialGroup()
                                    .addGroup(jPanelDatosActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelFechaAc)
                                        .addComponent(jLabelIDActiv))
                                    .addGap(37, 37, 37))
                                .addGroup(jPanelDatosActividadLayout.createSequentialGroup()
                                    .addComponent(jLabelHoraIni)
                                    .addGap(12, 12, 12)))
                            .addGroup(jPanelDatosActividadLayout.createSequentialGroup()
                                .addComponent(jLabelDificultad)
                                .addGap(20, 20, 20)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanelDatosActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosActividadLayout.createSequentialGroup()
                                .addGroup(jPanelDatosActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldInputIDActividad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldInputFechaActiv, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldInputHoraInicioAc))
                                .addGap(27, 27, 27))
                            .addGroup(jPanelDatosActividadLayout.createSequentialGroup()
                                .addComponent(jSpinnerDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanelDatosActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCapacidad)
                            .addComponent(jLabelDiaSemana)
                            .addComponent(jLabelNombreAc, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHoraFin))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDatosActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldInputDiaSemana, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldInputHoraFinActiv, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinnerCapacidadActiv, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldInputNombreActiv, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelDatosActividadLayout.createSequentialGroup()
                        .addComponent(jLabelDescripAc)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelDatosActividadLayout.createSequentialGroup()
                        .addComponent(jLabelNombreGuia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jTextFieldInputNombreGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelDatosActividadLayout.setVerticalGroup(
            jPanelDatosActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosActividadLayout.createSequentialGroup()
                .addGroup(jPanelDatosActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIDActiv)
                    .addComponent(jTextFieldInputIDActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreAc)
                    .addComponent(jTextFieldInputNombreActiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInputDiaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDiaSemana)
                    .addComponent(jTextFieldInputFechaActiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaAc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInputHoraInicioAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHoraIni)
                    .addComponent(jTextFieldInputHoraFinActiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHoraFin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerCapacidadActiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCapacidad)
                    .addComponent(jSpinnerDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDificultad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInputLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLocalizacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInputNombreGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreGuia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDescripAc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelDatosActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jButton1)
                        .addGap(37, 37, 37)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelMainTitulo)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMainTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDatosActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaSeleccion.setActividad(actividad);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabelCapacidad;
    private javax.swing.JLabel jLabelDescripAc;
    private javax.swing.JLabel jLabelDiaSemana;
    private javax.swing.JLabel jLabelDificultad;
    private javax.swing.JLabel jLabelFechaAc;
    private javax.swing.JLabel jLabelHoraFin;
    private javax.swing.JLabel jLabelHoraIni;
    private javax.swing.JLabel jLabelIDActiv;
    private javax.swing.JLabel jLabelLocalizacion;
    private javax.swing.JLabel jLabelMainTitulo;
    private javax.swing.JLabel jLabelNombreAc;
    private javax.swing.JLabel jLabelNombreGuia;
    private javax.swing.JPanel jPanelDatosActividad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerCapacidadActiv;
    private javax.swing.JSpinner jSpinnerDificultad;
    private javax.swing.JTextField jTextFieldInputDiaSemana;
    private javax.swing.JTextField jTextFieldInputFechaActiv;
    private javax.swing.JTextField jTextFieldInputHoraFinActiv;
    private javax.swing.JTextField jTextFieldInputHoraInicioAc;
    private javax.swing.JTextField jTextFieldInputIDActividad;
    private javax.swing.JTextField jTextFieldInputLocalizacion;
    private javax.swing.JTextField jTextFieldInputNombreActiv;
    private javax.swing.JTextField jTextFieldInputNombreGuia;
    private javax.swing.JTextPane jTextPaneInputDescrip;
    // End of variables declaration//GEN-END:variables
}
