/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.swing.vista;

import aplicacion.facade.Facade;
import dto.Alojamiento;
import dto.VistaActividadesAlojamiento;
import dto.VistaActividadesAlojamientoId;
import javax.swing.JOptionPane;
import org.hibernate.Session;

/**
 * Ventana para comprobar los datos del Alojamiento introducido y confirmar.
 * @author Mario Codes Sánchez
 * @since 21/02/2017
 */
public class VentanaCheckAlojamientoVista extends javax.swing.JFrame {
    private Alojamiento alojamiento;
    
    /**
     * Creates new form VentanaAltaAlojamiento
     * @param alojamiento Alojamiento del cual se obtienen los datos.
     */
    public VentanaCheckAlojamientoVista(Alojamiento alojamiento) {
        initComponents();
        
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        this.alojamiento = alojamiento;
        
        setDatos(this.alojamiento);
    }

    private void setDatos(Alojamiento alojamiento) {
        String nombre = alojamiento.getNombre();
        String telefono = alojamiento.getTelefonoContacto();
        String dirSoc = alojamiento.getDireccionSocial();
        String razSoc = alojamiento.getRazonSocial();
        int valoracion = alojamiento.getValoracion();
        String apertura = alojamiento.getFechaApertura();
        int habitaciones = alojamiento.getNumHabitaciones();
        String provincia = alojamiento.getProvincia();
        String descripcion = alojamiento.getDescripcion();
        
        if(nombre != null) this.jTextFieldInputNombreAloj.setText(nombre);
        if(telefono != null) this.jTextFieldInputTelefono.setText(telefono);
        if(dirSoc != null) this.jTextFieldInputDirSocial.setText(dirSoc);
        if(razSoc != null) this.jTextFieldInputRazonSocial.setText(razSoc);
        this.jSpinnerValoracion.setValue(valoracion);
        if(apertura != null) this.jTextFieldInputFechaApertura.setText(apertura);
        this.jSpinnerHabitaciones.setValue(habitaciones);
        if(provincia != null) this.jComboBoxProvincia.setSelectedItem(nombre);
        if(descripcion != null) this.jTextPaneInputDescripcionAloj.setText(descripcion);
    }
    
    private VistaActividadesAlojamientoId getDatos() {
        String nombre = this.jTextFieldInputNombreAloj.getText();
        String telefono = this.jTextFieldInputTelefono.getText();
        String dirSoc = this.jTextFieldInputDirSocial.getText();
        String razSoc = this.jTextFieldInputRazonSocial.getText();
        int valoracion = (int) this.jSpinnerValoracion.getValue();
        String apertura = this.jTextFieldInputFechaApertura.getText();
        int habitaciones = (int) this.jSpinnerHabitaciones.getValue();
        String provincia = this.jComboBoxProvincia.getSelectedItem().toString();
        String descripcion = this.jTextPaneInputDescripcionAloj.getText();
        
        return new VistaActividadesAlojamientoId(0, 6, nombre, descripcion, dirSoc, razSoc, telefono, valoracion, apertura, habitaciones, provincia, "", "", "", "", "", "", "", 0, "", "");
    }
    
    private boolean alta(VistaActividadesAlojamientoId id) {
        Session s = Facade.abrirSessionHibernate();
        
        VistaActividadesAlojamiento vaa = new VistaActividadesAlojamiento(id);
        s.save(vaa);
        
        return Facade.cerrarSessionHibernate(s);
    }
    
    private boolean checkObligatorios() {
        return !(this.jTextFieldInputNombreAloj.getText().isEmpty() && this.jTextFieldInputDirSocial.getText().isEmpty());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDatosAlojamiento = new javax.swing.JPanel();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldInputTelefono = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldInputNombreAloj = new javax.swing.JTextField();
        jTextFieldInputDirSocial = new javax.swing.JTextField();
        jLabelDirSocial = new javax.swing.JLabel();
        jTextFieldInputRazonSocial = new javax.swing.JTextField();
        jLabelRazonSocial = new javax.swing.JLabel();
        jSpinnerValoracion = new javax.swing.JSpinner();
        jLabelValoracion = new javax.swing.JLabel();
        jLabelFechaApertura = new javax.swing.JLabel();
        jTextFieldInputFechaApertura = new javax.swing.JTextField();
        jLabelHabitaciones = new javax.swing.JLabel();
        jSpinnerHabitaciones = new javax.swing.JSpinner();
        jLabelProvincia = new javax.swing.JLabel();
        jComboBoxProvincia = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneInputDescripcionAloj = new javax.swing.JTextPane();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabelMainTitulo = new javax.swing.JLabel();
        jButtonAceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelDatosAlojamiento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Alojamiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 2, 12))); // NOI18N

        jLabelTelefono.setText("Telefono");

        jTextFieldInputTelefono.setEnabled(false);

        jLabelNombre.setText("Nombre");

        jTextFieldInputNombreAloj.setEnabled(false);

        jTextFieldInputDirSocial.setEnabled(false);

        jLabelDirSocial.setText("Dir. Social");

        jTextFieldInputRazonSocial.setEnabled(false);

        jLabelRazonSocial.setText("Razon Social");

        jSpinnerValoracion.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        jSpinnerValoracion.setEnabled(false);

        jLabelValoracion.setText("Valoracion");

        jLabelFechaApertura.setText("Fecha Apertura");

        jTextFieldInputFechaApertura.setEnabled(false);

        jLabelHabitaciones.setText("Habitaciones");

        jSpinnerHabitaciones.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jSpinnerHabitaciones.setEnabled(false);

        jLabelProvincia.setText("Provincia");

        jComboBoxProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Huesca", "Zaragoza", "Teruel" }));
        jComboBoxProvincia.setEnabled(false);

        jTextPaneInputDescripcionAloj.setEnabled(false);
        jScrollPane2.setViewportView(jTextPaneInputDescripcionAloj);

        jLabelDescripcion.setText("Descripcion");

        javax.swing.GroupLayout jPanelDatosAlojamientoLayout = new javax.swing.GroupLayout(jPanelDatosAlojamiento);
        jPanelDatosAlojamiento.setLayout(jPanelDatosAlojamientoLayout);
        jPanelDatosAlojamientoLayout.setHorizontalGroup(
            jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosAlojamientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelDatosAlojamientoLayout.createSequentialGroup()
                            .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelValoracion)
                                .addComponent(jLabelHabitaciones))
                            .addGap(12, 12, 12)
                            .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelDatosAlojamientoLayout.createSequentialGroup()
                                    .addComponent(jSpinnerHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelProvincia)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                    .addComponent(jComboBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelDatosAlojamientoLayout.createSequentialGroup()
                                    .addComponent(jSpinnerValoracion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelFechaApertura))))
                        .addComponent(jLabelDescripcion)
                        .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldInputFechaApertura, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelDatosAlojamientoLayout.createSequentialGroup()
                                .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelRazonSocial)
                                    .addComponent(jLabelDirSocial)
                                    .addComponent(jLabelTelefono)
                                    .addComponent(jLabelNombre))
                                .addGap(12, 12, 12)
                                .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldInputDirSocial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                    .addComponent(jTextFieldInputTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldInputNombreAloj, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldInputRazonSocial)))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosAlojamientoLayout.setVerticalGroup(
            jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosAlojamientoLayout.createSequentialGroup()
                .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldInputNombreAloj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInputTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInputDirSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDirSocial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInputRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRazonSocial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerValoracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelValoracion)
                    .addComponent(jLabelFechaApertura)
                    .addComponent(jTextFieldInputFechaApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHabitaciones)
                    .addComponent(jSpinnerHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProvincia)
                    .addComponent(jComboBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabelDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelMainTitulo.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelMainTitulo.setText("Comprobacion de Datos");

        jButtonAceptar.setText("Confirmar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelDatosAlojamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonAceptar)
                        .addGap(27, 27, 27)
                        .addComponent(jButton2)
                        .addGap(110, 110, 110))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMainTitulo)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMainTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDatosAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        VentanaSeleccion.setAlojamiento(this.alojamiento);
        this.dispose();
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JComboBox jComboBoxProvincia;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelDirSocial;
    private javax.swing.JLabel jLabelFechaApertura;
    private javax.swing.JLabel jLabelHabitaciones;
    private javax.swing.JLabel jLabelMainTitulo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelProvincia;
    private javax.swing.JLabel jLabelRazonSocial;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelValoracion;
    private javax.swing.JPanel jPanelDatosAlojamiento;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerHabitaciones;
    private javax.swing.JSpinner jSpinnerValoracion;
    private javax.swing.JTextField jTextFieldInputDirSocial;
    private javax.swing.JTextField jTextFieldInputFechaApertura;
    private javax.swing.JTextField jTextFieldInputNombreAloj;
    private javax.swing.JTextField jTextFieldInputRazonSocial;
    private javax.swing.JTextField jTextFieldInputTelefono;
    private javax.swing.JTextPane jTextPaneInputDescripcionAloj;
    // End of variables declaration//GEN-END:variables
}
