/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.swing.vista;

import aplicacion.facade.Facade;
import controlador.datos.Singleton;
import dto.Actividad;
import dto.Alojamiento;
import dto.VistaActividadesAlojamiento;
import dto.VistaActividadesAlojamientoId;
import javax.swing.JOptionPane;
import org.hibernate.Query;
import org.hibernate.Session;
import vista.swing.comun.VentanaPrincipal;

/**
 * Ventana para dar de alta en la vidsta.
 * @author Mario Codes Sánchez
 * @since 21/02/2017
 */
public class VentanaSeleccion extends javax.swing.JFrame {
    private final boolean ALTA; //Si estamos en la version de alta o en la de baja.
    private final VentanaPrincipal VP = Singleton.getVentanaPrincipalObtencionSingleton();
    private static Alojamiento alojamiento;
    private static Actividad actividad;
    
    /**
     * Creates new form VentanaSeleccion
     */
    public VentanaSeleccion(boolean alta) {
        initComponents();
        
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setTitle("Seleccionar Elementos");
        
        this.ALTA = alta;
        this.jButton4.setEnabled(alta);
        this.jButton5.setEnabled(!alta);
    }

    private Alojamiento getAlojamiento(int pk) {
        Session s = Facade.abrirSessionHibernate();
        Query q = s.createQuery("FROM Alojamiento "
                + "WHERE id_alojamiento = :idAloj");
        q.setParameter("idAloj", pk);
        return (Alojamiento) q.uniqueResult();
    }
    
    private Actividad getActividad(int pk) {
        Session s = Facade.abrirSessionHibernate();
        Query q = s.createQuery("FROM Actividad "
                + "WHERE id_actividad = :idActiv");
        q.setParameter("idActiv", pk);
        return (Actividad) q.uniqueResult();
    }
    
    private boolean alta(Alojamiento alojamiento, Actividad actividad) {
        Session s = Facade.abrirSessionHibernate();
        VistaActividadesAlojamientoId vId = new VistaActividadesAlojamientoId();
        vId.setIdAlojamiento(alojamiento.getIdAlojamiento());
        vId.setIdActividad(actividad.getIdActividad());
        
        s.save(new VistaActividadesAlojamiento(vId));
        return Facade.cerrarSessionHibernate(s);
    }
    
    private boolean baja(Alojamiento alojamiento, Actividad actividad) {
        Session s = Facade.abrirSessionHibernate();
        
        Query q = s.createQuery("from VistaActividadesAlojamiento "
                                    + "where ID_ALOJAMIENTO = :idAloj "
                                    + "and id_actividad = :idActiv");
        q.setParameter("idAloj", alojamiento.getIdAlojamiento());
        q.setParameter("idActiv", actividad.getIdActividad());
        
        VistaActividadesAlojamiento va = (VistaActividadesAlojamiento) q.uniqueResult();
        
        if(va != null) s.delete(va);
        else return false;
//        VistaActividadesAlojamientoId vId = new VistaActividadesAlojamientoId();
//        vId.setIdAlojamiento(alojamiento.getIdAlojamiento());
//        vId.setIdActividad(actividad.getIdActividad());
//        s.delete(new VistaActividadesAlojamiento(vId));
        
        return Facade.cerrarSessionHibernate(s);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelAlojamiento = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Seleccionar Alojamiento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Seleccionar Actividad");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Realizar Alta");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setText("Alojamiento: ");

        jLabel4.setText("Actividad: ");

        jButton5.setText("Realizar Baja");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jLabelAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        VP.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int id = Integer.parseInt(JOptionPane.showInputDialog("ID de Alojamiento"));
            Alojamiento alojamiento = getAlojamiento(id);
            if(alojamiento != null) new VentanaCheckAlojamientoVista(alojamiento);
            else JOptionPane.showMessageDialog(this, "Problemas con el Alojamiento. Compruebe que existe.");
        }catch(NumberFormatException ex) {
            System.out.println("Excepcion de parse de numero al cancelar capturada. Es normal.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            int id = Integer.parseInt(JOptionPane.showInputDialog("ID de Actividad"));
            Actividad actividad = getActividad(id);
            if(actividad != null) new VentanaAltaActividadVista(actividad);
            else JOptionPane.showMessageDialog(this, "Problemas con la Actividad. Compruebe que exista");
        }catch(NumberFormatException ex) {
            System.out.println("Excepcion de parse de numero al cancelar capturada. Es normal.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(VentanaSeleccion.jLabelAlojamiento.getText().isEmpty() | VentanaSeleccion.jLabel5.getText().isEmpty()) JOptionPane.showMessageDialog(this, "Selecciona dos elementos validos.");
        else {
            int confirmacion = JOptionPane.showConfirmDialog(this, "Se añadira la actividad " +actividad.getNombre() +" en el alojamiento " +alojamiento.getNombre() +". ¿Seguro?");
            if(confirmacion == 0) {
                if(alta(alojamiento, actividad)) JOptionPane.showMessageDialog(this, "Relacion añadida.");
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(VentanaSeleccion.jLabelAlojamiento.getText().isEmpty() | VentanaSeleccion.jLabel5.getText().isEmpty()) JOptionPane.showMessageDialog(this, "Selecciona dos elementos validos.");
        else {
            int confirmacion = JOptionPane.showConfirmDialog(this, "Se borrara la relacion entre la actividad " +actividad.getNombre() +" y el alojamiento " +alojamiento.getNombre() +". ¿Seguro?");
            if(confirmacion == 0) {
                if(baja(alojamiento, actividad)) JOptionPane.showMessageDialog(this, "Relacion eliminada.");
                else JOptionPane.showMessageDialog(this, "Problema con alguno de los elementos. Por favor comprueba que la relacion entre ambos existe.");
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed
    
    /**
     * @return the alojamiento
     */
    public static Alojamiento getAlojamiento() {
        return alojamiento;
    }

    /**
     * @param aAlojamiento the alojamiento to set
     */
    public static void setAlojamiento(Alojamiento aAlojamiento) {
        alojamiento = aAlojamiento;
        VentanaSeleccion.jLabelAlojamiento.setText(alojamiento.getNombre());
    }
    
    /**
     * @return the actividad
     */
    public static Actividad getActividad() {
        return actividad;
    }

    /**
     * @param aActividad the actividad to set
     */
    public static void setActividad(Actividad aActividad) {
        actividad = aActividad;
        VentanaSeleccion.jLabel5.setText(actividad.getNombre());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private static javax.swing.JLabel jLabel5;
    private static javax.swing.JLabel jLabelAlojamiento;
    // End of variables declaration//GEN-END:variables
}
